// This file was generated by the Causa command line. Do not edit it manually.

import { AllowMissing } from '@causa/workspace/validation';
import { Type } from 'class-transformer';
import {
  Allow,
  IsArray,
  IsDefined,
  IsIn,
  IsObject,
  IsString,
  ValidateNested,
} from 'class-validator';

/**
 * The type of the input value.
 */
export enum TimelineInputType {
  String = 'string',
}

/**
 * Declaration of a single input accepted by a timeline.
 * Inputs can be referenced as `${ input('<name>') }` in source filters.
 */
export class TimelineInput {
  constructor(init: TimelineInput) {
    Object.assign(this, init);
  }

  /**
   * A human-readable description of the input.
   */
  @AllowMissing()
  @IsString()
  readonly description?: string;

  /**
   * The type of the input value.
   */
  @IsIn(['string'])
  readonly type!: TimelineInputType;

  /**
   * The default value to use when the input is not provided.
   */
  @AllowMissing()
  @IsString()
  readonly default?: string;
}

/**
 * The type of source.
 */
export enum TimelineSourceType {
  ServiceLogs = 'serviceLogs',
  EventTopic = 'eventTopic',
}

/**
 * A `json-e` template, expressed either as a string or an object.
 * Rendered against the relevant context and expected to evaluate to a string.
 */
export type TimelineTemplate = string | Record<string, any>;

/**
 * A single source in a timeline view.
 */
export class TimelineSource {
  constructor(init: TimelineSource) {
    Object.assign(this, init);
  }

  /**
   * An ID for the source.
   */
  @IsString()
  readonly id!: string;

  /**
   * The type of source.
   */
  @IsIn(['serviceLogs', 'eventTopic'])
  readonly type!: TimelineSourceType;

  /**
   * What the backing function queries:
   * - `serviceLogs`: the service container ID.
   * - `eventTopic`: the event topic ID.
   */
  @IsString()
  readonly target!: string;

  /**
   * A human-readable label.
   */
  @AllowMissing()
  @IsString()
  readonly name?: string;

  /**
   * The source's color, used to tint its lane and records.
   * Either a CSS hex string (`#rrggbb`), or a `json-e` template rendered against each record.
   * A hex result is used as-is, any other value is hashed to a stable color, so equal values share a color.
   */
  @AllowMissing()
  readonly color?: TimelineTemplate;

  /**
   * Implementation-specific filter expression forwarded to the backing query function.
   * A `json-e` template rendered against the timeline's inputs (`${ input('<name>') }`) and expected to evaluate to a string.
   */
  @AllowMissing()
  readonly filter?: TimelineTemplate;

  /**
   * A `json-e` template rendered against each raw record to produce the entry's one-line title.
   * Expected to evaluate to a string.
   */
  @Allow()
  readonly title!: TimelineTemplate;

  /**
   * A `json-e` template rendered against each raw record to produce the entry's body.
   */
  @Allow()
  readonly body!: TimelineTemplate;
}

/**
 * A Timeline view definition.
 */
export class Timeline {
  constructor(init: Timeline) {
    Object.assign(this, init);
  }

  /**
   * The display name of the timeline.
   */
  @IsString()
  readonly name!: string;

  /**
   * A Markdown description.
   */
  @AllowMissing()
  @IsString()
  readonly description?: string;

  /**
   * Inputs accepted by the timeline, keyed by input name.
   * Referenced as `${ input('<name>') }` in source filters.
   */
  @AllowMissing()
  @IsObject()
  readonly inputs?: Record<string, TimelineInput>;

  /**
   * The sources to display in the timeline.
   */
  @IsArray()
  @IsDefined()
  @IsObject({ each: true })
  @Type(() => TimelineSource)
  @ValidateNested()
  readonly sources!: TimelineSource[];
}
