// This file was generated by the Causa command line. Do not edit it manually.

import { AllowMissing as _CausaRuntimeAllowMissing } from '@causa/workspace/validation';
import { Type as _ClassTransformerType } from 'class-transformer';
import {
  Allow as _ClassValidatorAllow,
  IsArray as _ClassValidatorIsArray,
  IsDefined as _ClassValidatorIsDefined,
  IsIn as _ClassValidatorIsIn,
  IsObject as _ClassValidatorIsObject,
  IsString as _ClassValidatorIsString,
  ValidateNested as _ClassValidatorValidateNested,
} from 'class-validator';

/**
 * The type of the input value.
 */
export enum TimelineInputType {
  String = 'string',
}

/**
 * Declaration of a single input accepted by a timeline.
 * Inputs can be referenced as `${ input('<name>') }` in source filters.
 */
export class TimelineInput {
  constructor(init: TimelineInput) {
    Object.assign(this, init);
  }

  /**
   * A human-readable description of the input.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly description?: string;

  /**
   * The type of the input value.
   */
  @_ClassValidatorIsIn(['string'])
  readonly type!: TimelineInputType;

  /**
   * The default value to use when the input is not provided.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly default?: string;
}

/**
 * The type of source.
 */
export enum TimelineSourceType {
  ServiceLogs = 'serviceLogs',
  EventTopic = 'eventTopic',
}

/**
 * A `json-e` template, expressed either as a string or an object.
 * Rendered against the relevant context and expected to evaluate to a string.
 */
export type TimelineTemplate = string | Record<string, any>;

/**
 * A single source in a timeline view.
 */
export class TimelineSource {
  constructor(init: TimelineSource) {
    Object.assign(this, init);
  }

  /**
   * An ID for the source.
   */
  @_ClassValidatorIsString()
  readonly id!: string;

  /**
   * The type of source.
   */
  @_ClassValidatorIsIn(['serviceLogs', 'eventTopic'])
  readonly type!: TimelineSourceType;

  /**
   * What the backing function queries:
   * - `serviceLogs`: the service container ID.
   * - `eventTopic`: the event topic ID.
   */
  @_ClassValidatorIsString()
  readonly target!: string;

  /**
   * A human-readable label.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly name?: string;

  /**
   * The source's color, used to tint its lane and records.
   * Either a CSS hex string (`#rrggbb`), or a `json-e` template rendered against each record.
   * A hex result is used as-is, any other value is hashed to a stable color, so equal values share a color.
   */
  @_CausaRuntimeAllowMissing()
  readonly color?: TimelineTemplate;

  /**
   * Implementation-specific filter expression forwarded to the backing query function.
   * A `json-e` template rendered against the timeline's inputs (`${ input('<name>') }`) and expected to evaluate to a string.
   */
  @_CausaRuntimeAllowMissing()
  readonly filter?: TimelineTemplate;

  /**
   * A `json-e` template rendered against each raw record to produce the entry's one-line title.
   * Expected to evaluate to a string.
   */
  @_ClassValidatorAllow()
  readonly title!: TimelineTemplate;

  /**
   * A `json-e` template rendered against each raw record to produce the entry's body.
   */
  @_ClassValidatorAllow()
  readonly body!: TimelineTemplate;
}

/**
 * A Timeline view definition.
 */
export class Timeline {
  constructor(init: Timeline) {
    Object.assign(this, init);
  }

  /**
   * The display name of the timeline.
   */
  @_ClassValidatorIsString()
  readonly name!: string;

  /**
   * A Markdown description.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly description?: string;

  /**
   * Inputs accepted by the timeline, keyed by input name.
   * Referenced as `${ input('<name>') }` in source filters.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly inputs?: Record<string, TimelineInput>;

  /**
   * The sources to display in the timeline.
   */
  @_ClassTransformerType(() => TimelineSource)
  @_ClassValidatorIsArray()
  @_ClassValidatorIsDefined()
  @_ClassValidatorIsObject({ each: true })
  @_ClassValidatorValidateNested()
  readonly sources!: TimelineSource[];
}
