// This file was generated by the Causa command line. Do not edit it manually.

import {
  AllowMissing as _CausaRuntimeAllowMissing,
  IsNullable as _CausaRuntimeIsNullable,
} from '@causa/workspace/validation';
import { Type as _ClassTransformerType } from 'class-transformer';
import {
  Allow as _ClassValidatorAllow,
  IsArray as _ClassValidatorIsArray,
  IsBoolean as _ClassValidatorIsBoolean,
  IsDate as _ClassValidatorIsDate,
  IsDefined as _ClassValidatorIsDefined,
  IsIn as _ClassValidatorIsIn,
  IsInt as _ClassValidatorIsInt,
  IsNumber as _ClassValidatorIsNumber,
  IsObject as _ClassValidatorIsObject,
  IsString as _ClassValidatorIsString,
  ValidateNested as _ClassValidatorValidateNested,
} from 'class-validator';

/**
 * The payload of an `accesses` edge.
 */
export class AccessesGraphEdgeData {
  constructor(init: AccessesGraphEdgeData) {
    Object.assign(this, init);
  }

  /**
   * Whether the access includes reading. Absent means `true`.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsBoolean()
  readonly read?: boolean;

  /**
   * Whether the access includes writing. Absent means `true`.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsBoolean()
  readonly write?: boolean;
}

/**
 * The payload of a `brokerSubscription` node.
 */
export class BrokerSubscriptionGraphNodeData {
  constructor(init: BrokerSubscriptionGraphNodeData) {
    Object.assign(this, init);
  }

  /**
   * The broker-side filter narrowing which messages the subscription receives,
   * in the broker's own expression syntax.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly filter?: string;

  [key: string]: any;
}

/**
 * The payload of a `database` node.
 */
export class DatabaseGraphNodeData {
  constructor(init: DatabaseGraphNodeData) {
    Object.assign(this, init);
  }

  /**
   * The database engine, as Causa names it in database bindings.
   */
  @_ClassValidatorIsString()
  readonly engine!: string;

  [key: string]: any;
}

/**
 * The severity of the alert, when the provider sets one. From most to least
 * severe:
 * - `critical`: the resource is down or losing data, and needs immediate
 *   action.
 * - `error`: part of the traffic or processing is failing, and needs action
 *   soon.
 * - `warning`: the resource is degraded or at risk, and should be looked
 *   into.
 * - `info`: notable, but no action is needed.
 */
export enum GraphAlertSeverity {
  Critical = 'critical',
  Error = 'error',
  Warning = 'warning',
  Info = 'info',
}

/**
 * An alert raised by the provider's monitoring, open at the end of the
 * environment's evaluation window.
 */
export class GraphAlert {
  constructor(init: GraphAlert) {
    Object.assign(this, init);
  }

  /**
   * What the alert is about, e.g. the display name of the alerting policy that
   * raised it, or the error of a group of errors.
   */
  @_ClassValidatorIsString()
  readonly title!: string;

  /**
   * The severity of the alert, when the provider sets one. From most to least
   * severe:
   * - `critical`: the resource is down or losing data, and needs immediate
   *   action.
   * - `error`: part of the traffic or processing is failing, and needs action
   *   soon.
   * - `warning`: the resource is degraded or at risk, and should be looked
   *   into.
   * - `info`: notable, but no action is needed.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsIn(['critical', 'error', 'warning', 'info'])
  readonly severity?: GraphAlertSeverity;

  /**
   * When the alert was opened.
   */
  @_ClassTransformerType(() => Date)
  @_ClassValidatorIsDate()
  readonly openedAt!: Date;

  /**
   * The page of the alert in the provider's console.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly url?: string;
}

/**
 * The bucket layouts of distributions, keyed by name.
 *
 * A layout is a list of ascending bounds, in the unit of the metric. N bounds
 * define N + 1 buckets: bucket 0 holds values below the first bound, bucket i
 * holds values at or above bound i - 1 and below bound i, and bucket N holds
 * values at or above the last bound. Only distributions with the same layout
 * can be merged.
 */
export class GraphBucketLayouts {
  constructor(init: GraphBucketLayouts) {
    Object.assign(this, init);
  }

  [key: string]: number[] | any;
}

/**
 * A histogram of the values measured during the evaluation window.
 *
 * Distributions using the same bucket layout can be merged by summing
 * their counts.
 */
export class GraphDistribution {
  constructor(init: GraphDistribution) {
    Object.assign(this, init);
  }

  /**
   * The name of the bucket layout, in the graph's `bucketLayouts`.
   */
  @_ClassValidatorIsString()
  readonly layout!: string;

  /**
   * The number of measured values.
   */
  @_ClassValidatorIsInt()
  readonly count!: number;

  /**
   * The mean of the measured values.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsNumber()
  readonly mean?: number;

  /**
   * The counts of non-empty buckets, keyed by bucket index.
   */
  @_ClassValidatorIsObject()
  readonly buckets!: Record<string, number>;
}

/**
 * The environment from which data and metrics were added to the graph.
 *
 * Data, e.g. alerts, describes the environment at `at`. Metrics are
 * point-in-time values, computed over the window ending at `at`.
 */
export class GraphEnvironment {
  constructor(init: GraphEnvironment) {
    Object.assign(this, init);
  }

  /**
   * The ID of the Causa environment.
   */
  @_ClassValidatorIsString()
  readonly name!: string;

  /**
   * The end of the evaluation window.
   */
  @_ClassTransformerType(() => Date)
  @_ClassValidatorIsDate()
  readonly at!: Date;

  /**
   * The length of the evaluation window, in seconds.
   */
  @_ClassValidatorIsInt()
  readonly window!: number;

  /**
   * The alerts open at `at` that could not be attached to a node of the graph,
   * e.g. because their resource is not part of it.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => GraphAlert)
  @_ClassValidatorIsArray()
  @_ClassValidatorIsObject({ each: true })
  @_ClassValidatorValidateNested()
  readonly alerts?: GraphAlert[];
}

/**
 * A link to a web page about a node.
 */
export class GraphLink {
  constructor(init: GraphLink) {
    Object.assign(this, init);
  }

  /**
   * The text of the link.
   */
  @_ClassValidatorIsString()
  readonly label!: string;

  /**
   * The URL of the page.
   */
  @_ClassValidatorIsString()
  readonly url!: string;
}

/**
 * The definitions of metrics, keyed by node type and then by metric name.
 */
export class GraphMetricDefinitions {
  constructor(init: GraphMetricDefinitions) {
    Object.assign(this, init);
  }

  [key: string]: Record<string, GraphMetricDefinition> | any;
}

/**
 * How a metric value is computed over the evaluation window.
 * - `rate`: a count per second, averaged over the window.
 * - `gauge`: the latest value before the end of the window.
 * - `distribution`: a histogram of the values measured during the
 *   window.
 */
export enum GraphMetricKind {
  Rate = 'rate',
  Gauge = 'gauge',
  Distribution = 'distribution',
}

/**
 * The definition of a metric of a node type.
 *
 * Metrics are defined per node type, as the same name can differ in kind,
 * unit, and keys from one type to another.
 */
export class GraphMetricDefinition {
  constructor(init: GraphMetricDefinition) {
    Object.assign(this, init);
  }

  /**
   * The display name of the metric.
   */
  @_ClassValidatorIsString()
  readonly name!: string;

  /**
   * A Markdown description of the metric.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly description?: string;

  /**
   * How a metric value is computed over the evaluation window.
   * - `rate`: a count per second, averaged over the window.
   * - `gauge`: the latest value before the end of the window.
   * - `distribution`: a histogram of the values measured during the
   *   window.
   */
  @_ClassValidatorIsIn(['rate', 'gauge', 'distribution'])
  readonly kind!: GraphMetricKind;

  /**
   * The unit of the values, as a case-sensitive UCUM code, e.g. `ms`,
   * `By`, or `{request}/s`.
   */
  @_ClassValidatorIsString()
  readonly unit!: string;

  /**
   * The keys by which values of the metric may be grouped, with their
   * descriptions. Providers may group values by only some of them, or
   * none.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly groupBy?: Record<string, string>;
}

/**
 * A value of a metric: a number for rates and gauges, and a distribution for
 * distributions.
 */
export type GraphMetricMeasure = number | GraphDistribution;

/**
 * The value of a metric for a group.
 */
export class GraphMetricGroup {
  constructor(init: GraphMetricGroup) {
    Object.assign(this, init);
  }

  /**
   * The values of the keys defining the group, shown as they are.
   */
  @_ClassValidatorIsObject()
  readonly key!: Record<string, string>;

  /**
   * The value for the group.
   */
  @_ClassValidatorAllow()
  readonly value!: GraphMetricMeasure;
}

/**
 * The point-in-time value of a metric of a node, computed over the evaluation
 * window.
 */
export class GraphMetricValue {
  constructor(init: GraphMetricValue) {
    Object.assign(this, init);
  }

  /**
   * The total value.
   */
  @_ClassValidatorAllow()
  readonly value!: GraphMetricMeasure;

  /**
   * The keys by which `groups` are grouped.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsArray()
  @_ClassValidatorIsString({ each: true })
  readonly groupBy?: string[];

  /**
   * The value for each group.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => GraphMetricGroup)
  @_ClassValidatorIsArray()
  @_ClassValidatorIsObject({ each: true })
  @_ClassValidatorValidateNested()
  readonly groups?: GraphMetricGroup[];
}

/**
 * The type-specific payload of the node.
 */
export class GraphNodeData {
  constructor(init: GraphNodeData) {
    Object.assign(this, init);
  }

  /**
   * Links to web pages about the node, e.g. its resource in the provider's
   * console. Added when the graph is enriched with environment data.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => GraphLink)
  @_ClassValidatorIsArray()
  @_ClassValidatorIsObject({ each: true })
  @_ClassValidatorValidateNested()
  readonly links?: GraphLink[];

  /**
   * The alerts raised by the provider's monitoring for the node's
   * resource, open at the end of the evaluation window. Added when the
   * graph is enriched with environment data, and absent when no alert is
   * open.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => GraphAlert)
  @_ClassValidatorIsArray()
  @_ClassValidatorIsObject({ each: true })
  @_ClassValidatorValidateNested()
  readonly alerts?: GraphAlert[];

  [key: string]: any;
}

/**
 * How an element was extracted from its sources.
 * - `declared`: the workspace defines it, either verbatim (e.g. in
 *   configuration) or through deterministic, documented logic that other
 *   tools share.
 * - `inferred`: produced by a heuristic that may be wrong, or a language
 *   model enhancing the graph from a skill.
 * - `authored`: asserted by a person.
 */
export enum GraphOriginKind {
  Declared = 'declared',
  Inferred = 'inferred',
  Authored = 'authored',
}

/**
 * A line and column in a file, both 1-based.
 */
export class GraphSourcePosition {
  constructor(init: GraphSourcePosition) {
    Object.assign(this, init);
  }

  /**
   * The line number.
   */
  @_ClassValidatorIsInt()
  readonly line!: number;

  /**
   * The column number. Omitted to designate the whole line.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsInt()
  readonly column?: number;
}

/**
 * A position in a file, as a point or a range. Lines and columns are
 * 1-based, as editors display them.
 */
export class GraphSourceLocation {
  constructor(init: GraphSourceLocation) {
    Object.assign(this, init);
  }

  /**
   * Where the construct starts, or the point itself.
   */
  @_ClassTransformerType(() => GraphSourcePosition)
  @_ClassValidatorIsDefined()
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly start!: GraphSourcePosition;

  /**
   * Where the construct ends, inclusive. Omitted for a point rather than a
   * range.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => GraphSourcePosition)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly end?: GraphSourcePosition;
}

/**
 * A single location in the workspace an element was extracted from: a file
 * or directory, and optionally a position within a file.
 */
export class GraphOriginSource {
  constructor(init: GraphOriginSource) {
    Object.assign(this, init);
  }

  /**
   * The path of the file, or of the directory when the element is defined
   * by a directory as a whole (a domain by its folder, a database by its
   * folder of migrations), relative to the workspace root.
   */
  @_ClassValidatorIsString()
  readonly path!: string;

  /**
   * The construct within the file. Its syntax is decided by the file's
   * extension:
   *
   * - `.json`, `.yaml`, `.yml`: a JSON pointer.
   * - `.tf`: a Terraform address, e.g. `module.my_module`.
   * - Source files (`.ts`, `.js`, `.py`, …): a dotted symbol path, e.g.
   *   `MyClass.method`.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly pointer?: string;

  /**
   * The position of the construct in the file, as lines and columns.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => GraphSourceLocation)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly location?: GraphSourceLocation;
}

/**
 * The workspace files a node or edge was extracted from, how it was extracted,
 * and how much the result should be trusted.
 *
 * Every element of the graph is defined somewhere in the workspace: a
 * `causa.yaml` entry, a schema file, a Terraform module, a class in a service.
 * The origin records that definition, so the element can be traced back to it
 * and its reliability judged.
 */
export class GraphOrigin {
  constructor(init: GraphOrigin) {
    Object.assign(this, init);
  }

  /**
   * How the element was extracted from its sources.
   */
  @_ClassValidatorIsIn(['declared', 'inferred', 'authored'])
  readonly kind!: GraphOriginKind;

  /**
   * The locations in the workspace that define the element, most relevant
   * first. Used to navigate from the graph back to its definition.
   */
  @_ClassTransformerType(() => GraphOriginSource)
  @_ClassValidatorIsArray()
  @_ClassValidatorIsDefined()
  @_ClassValidatorIsObject({ each: true })
  @_ClassValidatorValidateNested()
  readonly sources!: GraphOriginSource[];

  /**
   * The name of the extraction rule that produced the element from its
   * sources.
   */
  @_ClassValidatorIsString()
  readonly rule!: string;
}

/**
 * A directed relation between two nodes, oriented in the direction data or
 * control flows.
 */
export class GraphEdge {
  constructor(init: GraphEdge) {
    Object.assign(this, init);
  }

  /**
   * The id of the source node, or `null` when the edge has no source.
   */
  @_CausaRuntimeIsNullable()
  @_ClassValidatorIsString()
  readonly from!: string | null;

  /**
   * The id of the destination node, or `null` when the edge has no
   * destination.
   */
  @_CausaRuntimeIsNullable()
  @_ClassValidatorIsString()
  readonly to!: string | null;

  /**
   * A short label rendered on the edge, e.g. the name of the event driving a
   * transition.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly label?: string;

  /**
   * A Markdown description.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly description?: string;

  /**
   * The workspace sources the edge was extracted from, how it was extracted,
   * and how much to trust it.
   */
  @_ClassTransformerType(() => GraphOrigin)
  @_ClassValidatorIsDefined()
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly origin!: GraphOrigin;

  /**
   * The type-specific payload of the edge.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly data?: Record<string, any>;
}

/**
 * The edges of a graph, keyed by type and then listed.
 */
export class GraphEdges {
  constructor(init: GraphEdges) {
    Object.assign(this, init);
  }

  /**
   * In the architecture layer, a project publishes to a `topic`, from
   * `serviceContainer.outputs.eventTopics`. In the infrastructure layer, a
   * `service` is granted publishing on a `brokerTopic`.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => GraphEdge)
  @_ClassValidatorIsArray()
  @_ClassValidatorIsObject({ each: true })
  @_ClassValidatorValidateNested()
  readonly publishes?: GraphEdge[];

  /**
   * A topic delivers messages to what consumes it. In the architecture layer,
   * a `topic` to a `trigger` whose `type` is `event`. In the infrastructure
   * layer, a `brokerTopic` to a `brokerSubscription`.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => GraphEdge)
  @_ClassValidatorIsArray()
  @_ClassValidatorIsObject({ each: true })
  @_ClassValidatorValidateNested()
  readonly delivers?: GraphEdge[];

  /**
   * An API router forwarding requests to services.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => GraphEdge)
  @_ClassValidatorIsArray()
  @_ClassValidatorIsObject({ each: true })
  @_ClassValidatorValidateNested()
  readonly routes?: GraphEdge[];

  /**
   * A party makes a request to another party. Requesters and responders can be
   * projects, services, third-party systems, clients, etc.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => GraphEdge)
  @_ClassValidatorIsArray()
  @_ClassValidatorIsObject({ each: true })
  @_ClassValidatorValidateNested()
  readonly calls?: GraphEdge[];

  /**
   * In the architecture layer, a project accesses an `entity`: the entities
   * whose tables live in a datastore the project owns
   * (`serviceContainer.outputs`). In the infrastructure layer, a `service` is
   * granted access to a `database` or `table`.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => GraphEdge)
  @_ClassValidatorIsArray()
  @_ClassValidatorIsObject({ each: true })
  @_ClassValidatorValidateNested()
  readonly accesses?: GraphEdge[];

  /**
   * In the architecture layer, a project enqueues work for one of its own
   * `task` triggers. In the infrastructure layer, a `service` is granted
   * enqueuing on the `queue` realizing that trigger.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => GraphEdge)
  @_ClassValidatorIsArray()
  @_ClassValidatorIsObject({ each: true })
  @_ClassValidatorValidateNested()
  readonly enqueues?: GraphEdge[];

  /**
   * A resource one layer down is the concrete form of a concept one layer up:
   * a `service` realizes a `project`, a `brokerTopic` a `topic`, etc.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => GraphEdge)
  @_ClassValidatorIsArray()
  @_ClassValidatorIsObject({ each: true })
  @_ClassValidatorValidateNested()
  readonly realizes?: GraphEdge[];

  /**
   * A `brokerSubscription`, `queue`, or `scheduledJob` targets what receives
   * it, e.g. a `service`.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => GraphEdge)
  @_ClassValidatorIsArray()
  @_ClassValidatorIsObject({ each: true })
  @_ClassValidatorValidateNested()
  readonly targets?: GraphEdge[];

  /**
   * A topic carries an entity: the `data` property of the topic's event
   * schema references it.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => GraphEdge)
  @_ClassValidatorIsArray()
  @_ClassValidatorIsObject({ each: true })
  @_ClassValidatorValidateNested()
  readonly carries?: GraphEdge[];

  /**
   * An entity moves from one state to another. Derived from an event
   * constraint's `entityMutationFrom` and the state its `data` property
   * references.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => GraphEdge)
  @_ClassValidatorIsArray()
  @_ClassValidatorIsObject({ each: true })
  @_ClassValidatorValidateNested()
  readonly transitions?: GraphEdge[];

  /**
   * An infrastructure project manages a resource, e.g. the Terraform project
   * that creates a service.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => GraphEdge)
  @_ClassValidatorIsArray()
  @_ClassValidatorIsObject({ each: true })
  @_ClassValidatorValidateNested()
  readonly deploys?: GraphEdge[];

  /**
   * An entity is projected into another entity: the destination is a local
   * view of the source, maintained from the source's event stream, usually
   * across a domain boundary.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => GraphEdge)
  @_ClassValidatorIsArray()
  @_ClassValidatorIsObject({ each: true })
  @_ClassValidatorValidateNested()
  readonly projects?: GraphEdge[];

  [key: string]: GraphEdge[] | any;
}

/**
 * A single node of the architecture graph.
 *
 * A node is anything that can be pointed at, navigated to, or measured: a
 * project, a service, an event topic, an entity, a state of that entity, etc.
 *
 * A node carries neither its type nor its id: both are given by its position in
 * `Nodes`. Its id is `<type>:<locator>`.
 */
export class GraphNode {
  constructor(init: GraphNode) {
    Object.assign(this, init);
  }

  /**
   * The id of the containing node. Absent on a root node.
   *
   * The parent of a node must be in the same layer.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly parent?: string;

  /**
   * The display name of the node.
   */
  @_ClassValidatorIsString()
  readonly name!: string;

  /**
   * A Markdown description, usually copied from the underlying declaration.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly description?: string;

  /**
   * The workspace sources the node was extracted from, how it was extracted,
   * and how much to trust it.
   */
  @_ClassTransformerType(() => GraphOrigin)
  @_ClassValidatorIsDefined()
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly origin!: GraphOrigin;

  /**
   * Free-form labels for concerns that cut across node types. For example:
   * - `pii`: the node holds or carries personal data.
   * - `deprecated`: a `v1` topic superseded by a `v2`, so its remaining
   *   consumers stand out.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsArray()
  @_ClassValidatorIsString({ each: true })
  readonly tags?: string[];

  /**
   * The type-specific payload of the node.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => GraphNodeData)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly data?: GraphNodeData;

  /**
   * The point-in-time values of the node's metrics, keyed by metric name.
   * Added when the graph is enriched with environment data.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly metrics?: Record<string, GraphMetricValue>;
}

/**
 * The architecture layer, keyed by type and then by locator.
 */
export class ArchitectureGraphNodes {
  constructor(init: ArchitectureGraphNodes) {
    Object.assign(this, init);
  }

  /**
   * A business domain grouping projects and schemas.
   *
   * Parent: none.
   *
   * Locator: the domain directory, relative to the workspace root, e.g.
   * `domains/my-domain`.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly domain?: Record<string, GraphNode>;

  /**
   * A Causa project, i.e. a directory with a `causa.yaml` defining
   * `project.name`.
   *
   * Parent: `domain` or none.
   *
   * Locator: the project directory, relative to the workspace root, e.g.
   * `domains/my-domain/service`.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly project?: Record<string, GraphNode>;

  /**
   * A single operation of a project's API (e.g. from an OpenAPI document).
   *
   * Parent: `project`.
   *
   * Locator: For OpenAPI operations, the `operationId`.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly apiOperation?: Record<string, GraphNode>;

  /**
   * An entry point of a service other than its API: an event subscription,
   * a schedule, a task queue, as declared in `serviceContainer.triggers`.
   *
   * Parent: `project`.
   *
   * Locator: `<project locator>#<trigger name>`, e.g.
   * `domains/my-domain/service#handleMyEntity`.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly trigger?: Record<string, GraphNode>;

  /**
   * An event topic.
   *
   * Parent: `domain` or none.
   *
   * Locator: the topic id as formatted by `events.topics.format`, e.g.
   * `my-domain.my-entity.v1`.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly topic?: Record<string, GraphNode>;

  /**
   * An object schema the system holds state for. This can be a business
   * concept published as events to a topic, or something persisted in a
   * database for a service to use.
   *
   * Parent: `domain` or none.
   *
   * Locator: the schema file path, with `#<JSON pointer>` appended for a
   * nested definition.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly entity?: Record<string, GraphNode>;

  /**
   * A state an entity can be in, defined by a constraint schema
   * (`causa.constraintFor`). States are children of the entity they
   * constrain.
   *
   * Parent: `entity`.
   *
   * Locator: the constraint schema's own address: its file path, with
   * `#<JSON pointer>` appended when it is a nested definition.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly state?: Record<string, GraphNode>;

  [key: string]: Record<string, GraphNode> | any;
}

/**
 * The HTTP method.
 */
export enum HttpMethod {
  Get = 'get',
  Put = 'put',
  Post = 'post',
  Delete = 'delete',
  Options = 'options',
  Head = 'head',
  Patch = 'patch',
  Trace = 'trace',
}

/**
 * The payload of an `apiOperation` node.
 */
export class ApiOperationGraphNodeData {
  constructor(init: ApiOperationGraphNodeData) {
    Object.assign(this, init);
  }

  /**
   * The HTTP method.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsIn([
    'get',
    'put',
    'post',
    'delete',
    'options',
    'head',
    'patch',
    'trace',
  ])
  readonly method?: HttpMethod;

  /**
   * The OpenAPI path template, e.g. `/myEntities/{id}`.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly path?: string;

  /**
   * Whether the operation is accessible without authentication.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsBoolean()
  readonly public?: boolean;
}

/**
 * The infrastructure layer, keyed by type and then by locator.
 */
export class InfrastructureGraphNodes {
  constructor(init: InfrastructureGraphNodes) {
    Object.assign(this, init);
  }

  /**
   * A deployed instance of a project. A single `serviceContainer` project
   * may be deployed several times, for example as a public API and as an
   * internal event handler.
   *
   * Parent: none or a module-provided node. A service `realizes` its
   * project.
   *
   * Locator: `<project locator>#<service name>`.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly service?: Record<string, GraphNode>;

  /**
   * The router exposing several services behind a load balancer.
   *
   * Parent: none or a module-provided node.
   *
   * Locator: the router's name.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly apiRouter?: Record<string, GraphNode>;

  /**
   * A message broker topic. Realizes a `topic`.
   *
   * Parent: none or a module-provided node.
   *
   * Locator: the topic id, the same as the architecture `topic` it
   * realizes.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly brokerTopic?: Record<string, GraphNode>;

  /**
   * A broker subscription: a topic `delivers` to it, and it `targets` to a
   * destination (e.g. a `service`). A subscription may realize a
   * `trigger`.
   *
   * Parent: none or a module-provided node.
   *
   * Locator: for a subscription realizing a trigger, `<project
   * locator>#<trigger name>`, the same as the trigger. Subscriptions can
   * be defined in other ways, and each such way brings its own locator
   * format, named after the feature that creates it.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly brokerSubscription?: Record<string, GraphNode>;

  /**
   * A task queue. Realizes a `trigger` of type `task` and `targets` to the
   * `service` that receives it.
   *
   * Parent: none or a module-provided node.
   *
   * Locator: the queue name, as declared on the trigger.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly queue?: Record<string, GraphNode>;

  /**
   * A scheduled job calling a service on a cron schedule. Realizes a
   * `trigger` of type `cron` and `targets` to the `service` that receives
   * it.
   *
   * Parent: none or a module-provided node.
   *
   * Locator: `<project locator>#<trigger name>`, the same as the trigger
   * it realizes.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly scheduledJob?: Record<string, GraphNode>;

  /**
   * A database composed of tables.
   *
   * Parent: none or a module-provided grouping.
   *
   * Locator: `<engine>/<name>`.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly database?: Record<string, GraphNode>;

  /**
   * A table within a database. Realizes the `entity` whose schema defines
   * it, when there is one.
   *
   * Parent: `database`.
   *
   * Locator: `<database locator>#<table>`.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly table?: Record<string, GraphNode>;

  [key: string]: Record<string, GraphNode> | any;
}

/**
 * The nodes of a graph, keyed by layer, then by type, then by locator.
 *
 * Layers are:
 *
 * - `architecture`: what the workspace declares: domains, projects, what they
 *   handle, the topics and entities they act on.
 * - `infrastructure`: the resources that realize the architecture: services,
 *   broker topics and subscriptions, queues, databases and tables.
 * - `model`: the schema documents behind the architecture. Empty today.
 * - `code`: the modules, classes, and methods that implement the architecture,
 *   parsed from source. Empty today.
 *
 * A node's id is `<type>:<locator>`, without the layer: types are unique across
 * layers.
 *
 * `parent` never crosses a layer. The relation between a resource and the
 * concept it stands for is the `realizes` edge.
 */
export class GraphNodes {
  constructor(init: GraphNodes) {
    Object.assign(this, init);
  }

  /**
   * The architecture layer, keyed by type and then by locator.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => ArchitectureGraphNodes)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly architecture?: ArchitectureGraphNodes;

  /**
   * The infrastructure layer, keyed by type and then by locator.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => InfrastructureGraphNodes)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly infrastructure?: InfrastructureGraphNodes;

  /**
   * The model layer: the schema documents that realize architecture concepts.
   * Empty today.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly model?: Record<string, Record<string, GraphNode>>;

  /**
   * The code layer: modules, classes, and methods that implement the
   * architecture, parsed from source. Empty today.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly code?: Record<string, Record<string, GraphNode>>;
}

/**
 * An architecture graph derived from a Causa workspace.
 *
 * A graph document may be a fragment: several documents can be merged (nodes
 * with nodes, edges with edges) to form the complete graph. This allows
 * splitting a large workspace by domain or by concern.
 */
export class Graph {
  constructor(init: Graph) {
    Object.assign(this, init);
  }

  /**
   * A human-readable name for this document, when it is a fragment of a larger
   * graph.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly name?: string;

  /**
   * A Markdown description of this document.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly description?: string;

  /**
   * The nodes, keyed by type and then by locator.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => GraphNodes)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly nodes?: GraphNodes;

  /**
   * The edges, keyed by type and then listed.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => GraphEdges)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly edges?: GraphEdges;

  /**
   * The environment from which data and metrics were added to the graph.
   * Absent from a graph that was not enriched with environment data.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => GraphEnvironment)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly environment?: GraphEnvironment;

  /**
   * The definitions of the metrics of the graph's nodes, keyed by node type
   * and then by metric name.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => GraphMetricDefinitions)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly metrics?: GraphMetricDefinitions;

  /**
   * The bucket layouts referenced by the distributions of the graph's metrics,
   * keyed by name.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => GraphBucketLayouts)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly bucketLayouts?: GraphBucketLayouts;
}

/**
 * The payload of a `project` node.
 */
export class ProjectGraphNodeData {
  constructor(init: ProjectGraphNodeData) {
    Object.assign(this, init);
  }

  /**
   * The `project.type` value, e.g. `serviceContainer`.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly type?: string;

  /**
   * The `project.language` value.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly language?: string;
}

/**
 * The entity properties this transition may change, from
 * `causa.entityPropertyChanges`.
 */
export type PropertyChanges = string[] | '*';

/**
 * The payload of a `routes` edge.
 */
export class RoutesGraphEdgeData {
  constructor(init: RoutesGraphEdgeData) {
    Object.assign(this, init);
  }

  /**
   * The path prefixes matched by the router.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsArray()
  @_ClassValidatorIsString({ each: true })
  readonly paths?: string[];
}

/**
 * The outcome of the attempt.
 * - `succeeded`: the target processed the call successfully.
 * - `failed`: the call failed, or the target returned an error.
 */
export enum ScheduledJobAttemptStatus {
  Succeeded = 'succeeded',
  Failed = 'failed',
}

/**
 * The last attempt of the job, added from the environment when the graph
 * is enriched.
 */
export class ScheduledJobLastAttempt {
  constructor(init: ScheduledJobLastAttempt) {
    Object.assign(this, init);
  }

  /**
   * When the attempt started.
   */
  @_ClassTransformerType(() => Date)
  @_ClassValidatorIsDate()
  readonly time!: Date;

  /**
   * The outcome of the attempt.
   * - `succeeded`: the target processed the call successfully.
   * - `failed`: the call failed, or the target returned an error.
   */
  @_ClassValidatorIsIn(['succeeded', 'failed'])
  readonly status!: ScheduledJobAttemptStatus;

  /**
   * The detail of the outcome, as given by the provider, e.g. why the
   * attempt failed.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly message?: string;
}

/**
 * The payload of a `scheduledJob` node.
 */
export class ScheduledJobGraphNodeData {
  constructor(init: ScheduledJobGraphNodeData) {
    Object.assign(this, init);
  }

  /**
   * The last attempt of the job, added from the environment when the graph
   * is enriched.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => ScheduledJobLastAttempt)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly lastAttempt?: ScheduledJobLastAttempt;

  /**
   * The next scheduled execution, added from the environment when the graph
   * is enriched.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => Date)
  @_ClassValidatorIsDate()
  readonly nextRun?: Date;

  [key: string]: any;
}

/**
 * The status of the latest deployment of the service.
 * - `deployed`: the latest deployment was applied, and is served.
 * - `deploying`: a deployment is in progress.
 * - `failed`: the latest deployment failed. The service may still serve
 *   a previous deployment.
 */
export enum ServiceDeploymentStatus {
  Deployed = 'deployed',
  Deploying = 'deploying',
  Failed = 'failed',
}

/**
 * What is deployed, added from the environment when the graph is enriched.
 */
export class ServiceDeployment {
  constructor(init: ServiceDeployment) {
    Object.assign(this, init);
  }

  /**
   * The deployed container image, including its tag.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly image?: string;

  /**
   * When the service was last updated.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => Date)
  @_ClassValidatorIsDate()
  readonly updatedAt?: Date;

  /**
   * The status of the latest deployment of the service.
   * - `deployed`: the latest deployment was applied, and is served.
   * - `deploying`: a deployment is in progress.
   * - `failed`: the latest deployment failed. The service may still serve
   *   a previous deployment.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsIn(['deployed', 'deploying', 'failed'])
  readonly status?: ServiceDeploymentStatus;

  /**
   * The reason for the status, as given by the provider, e.g. why the
   * latest deployment failed.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly message?: string;
}

/**
 * The payload of a `service` node.
 */
export class ServiceGraphNodeData {
  constructor(init: ServiceGraphNodeData) {
    Object.assign(this, init);
  }

  /**
   * The `serviceContainer.platform` value, e.g. `google.cloudRun`.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly platform?: string;

  /**
   * What is deployed, added from the environment when the graph is enriched.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => ServiceDeployment)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly deployment?: ServiceDeployment;

  [key: string]: any;
}

/**
 * The payload of a `transitions` edge.
 */
export class TransitionsGraphEdgeData {
  constructor(init: TransitionsGraphEdgeData) {
    Object.assign(this, init);
  }

  /**
   * The name of the event that performs the transition.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly eventName?: string;

  /**
   * The entity properties this transition may change, from
   * `causa.entityPropertyChanges`.
   */
  @_CausaRuntimeAllowMissing()
  readonly propertyChanges?: PropertyChanges;

  /**
   * The id of the `topic` node whose event performs this transition.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly topic?: string;
}

/**
 * The payload of a `trigger` node.
 */
export class TriggerGraphNodeData {
  constructor(init: TriggerGraphNodeData) {
    Object.assign(this, init);
  }

  /**
   * The `type` of the trigger, e.g. `event`, `cron`, `task`, etc.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly type?: string;

  /**
   * Whether the trigger is deployed. Defaults to `true`.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsBoolean()
  readonly enabled?: boolean;

  /**
   * The HTTP path the trigger calls on the service.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly path?: string;

  /**
   * The cron expression, for `cron` triggers.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly schedule?: string;

  /**
   * The timezone of the cron schedule. Defaults to UTC.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly timezone?: string;
}
