// This file was generated by the Causa command line. Do not edit it manually.

import { AllowMissing, IsNullable } from '@causa/workspace/validation';
import { Type } from 'class-transformer';
import {
  Allow,
  Equals,
  IsArray,
  IsDefined,
  IsIn,
  IsNumber,
  IsObject,
  IsString,
  ValidateNested,
} from 'class-validator';

/**
 * Additional causa properties used by workspace functions in this package.
 */
export class Causa {
  constructor(init: Causa) {
    Object.assign(this, init);
  }

  /**
   * The directory where project configurations are written by the ProjectWriteConfigurations processor.
   */
  @AllowMissing()
  @IsString()
  readonly projectConfigurationsDirectory?: string;

  [key: string]: any;
}

/**
 * A configuration with additional `causa` properties used by workspace functions in this package.
 */
export class CausaConfiguration {
  constructor(init: CausaConfiguration) {
    Object.assign(this, init);
  }

  /**
   * Additional causa properties used by workspace functions in this package.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => Causa)
  @ValidateNested()
  readonly causa?: Causa;

  [key: string]: any;
}

export class CodeGenerator {
  constructor(init: CodeGenerator) {
    Object.assign(this, init);
  }

  /**
   * The name of the generator to run.
   */
  @IsString()
  readonly generator!: string;

  [key: string]: any;
}

/**
 * Configuration for the local Docker network.
 */
export class DockerNetwork {
  constructor(init: DockerNetwork) {
    Object.assign(this, init);
  }

  /**
   * The name of the local Docker network.
   */
  @AllowMissing()
  @IsString()
  readonly name?: string;

  [key: string]: any;
}

/**
 * Configuration when using Docker in the workspace.
 */
export class Docker {
  constructor(init: Docker) {
    Object.assign(this, init);
  }

  /**
   * Configuration for the local Docker network.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => DockerNetwork)
  @ValidateNested()
  readonly network?: DockerNetwork;

  [key: string]: any;
}

/**
 * The schema for the configuration of Docker.
 */
export class DockerConfiguration {
  constructor(init: DockerConfiguration) {
    Object.assign(this, init);
  }

  /**
   * Configuration when using Docker in the workspace.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => Docker)
  @ValidateNested()
  readonly docker?: Docker;

  [key: string]: any;
}

/**
 * The format to which events are serialized when exchanged through the message broker.
 */
export enum EventsFormat {
  Json = 'json',
}

/**
 * Defines how topic definitions are found in the workspace.
 */
export class EventsTopics {
  constructor(init: EventsTopics) {
    Object.assign(this, init);
  }

  /**
   * The format string using groups from the regular expression used to make the topic full names.
   */
  @AllowMissing()
  @IsString()
  readonly format?: string;

  /**
   * A list of glob patterns to find topic schema definition files in the workspace.
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly globs?: string[];

  /**
   * The regular expression used to extract groups from the topic schemas file paths.
   */
  @AllowMissing()
  @IsString()
  readonly regularExpression?: string;

  [key: string]: any;
}

/**
 * Configuration for events and how they are exchanged between services.
 */
export class Events {
  constructor(init: Events) {
    Object.assign(this, init);
  }

  /**
   * The format to which events are serialized when exchanged through the message broker.
   */
  @AllowMissing()
  @IsIn(['json'])
  readonly format?: EventsFormat;

  /**
   * The message broker used to exchange events between services.
   */
  @AllowMissing()
  @IsString()
  readonly broker?: string;

  /**
   * Defines how topic definitions are found in the workspace.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => EventsTopics)
  @ValidateNested()
  readonly topics?: EventsTopics;

  [key: string]: any;
}

/**
 * Configuration for events.
 */
export class EventsConfiguration {
  constructor(init: EventsConfiguration) {
    Object.assign(this, init);
  }

  /**
   * Configuration for events and how they are exchanged between services.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => Events)
  @ValidateNested()
  readonly events?: Events;

  [key: string]: any;
}

/**
 * The schema format in which the model is defined.
 */
export enum ModelSchema {
  Jsonschema = 'jsonschema',
}

/**
 * Configuration for the business model definitions.
 */
export class Model {
  constructor(init: Model) {
    Object.assign(this, init);
  }

  /**
   * The schema format in which the model is defined.
   */
  @AllowMissing()
  @IsIn(['jsonschema'])
  readonly schema?: ModelSchema;

  /**
   * A list of glob patterns pointing to files containing the model definitions (schemas).
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly globs?: string[];

  /**
   * A list of code generators to run in a project when the `model generateCode` command is run.
   */
  @AllowMissing()
  @IsArray()
  @IsObject({ each: true })
  @Type(() => CodeGenerator)
  @ValidateNested()
  readonly codeGenerators?: CodeGenerator[];

  [key: string]: any;
}

export class ModelConfiguration {
  constructor(init: ModelConfiguration) {
    Object.assign(this, init);
  }

  /**
   * Configuration for the business model definitions.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => Model)
  @ValidateNested()
  readonly model?: Model;

  [key: string]: any;
}

/**
 * Configuration for OpenAPI specifications-related operations.
 */
export class OpenApi {
  constructor(init: OpenApi) {
    Object.assign(this, init);
  }

  /**
   * An OpenAPI specification file to be used as the base when generating the specification for the entire workspace.
   */
  @AllowMissing()
  @IsObject()
  readonly global?: Record<string, any>;

  /**
   * A list of glob patterns matching OpenAPI specification files to merge when generating the specification for a project.
   * The globs are resolved relative to the project directory.
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly specifications?: string[];

  /**
   * If set, the list of servers will be generated using a value from the configuration of each environment.
   * This should be the path to the configuration property containing the server URL.
   */
  @AllowMissing()
  @IsString()
  readonly serversFromEnvironmentConfiguration?: string;

  [key: string]: any;
}

/**
 * Configuration for OpenAPI specifications-related operations.
 */
export class OpenApiConfiguration {
  constructor(init: OpenApiConfiguration) {
    Object.assign(this, init);
  }

  /**
   * Configuration for OpenAPI specifications-related operations.
   */
  @AllowMissing()
  @IsNullable()
  @IsObject()
  @Type(() => OpenApi)
  @ValidateNested()
  readonly openApi?: OpenApi | null;

  [key: string]: any;
}

export class ProcessorInstruction {
  constructor(init: ProcessorInstruction) {
    Object.assign(this, init);
  }

  /**
   * The name of the WorkspaceFunction.
   */
  @IsString()
  readonly name!: string;

  /**
   * Arguments for the workspace function.
   */
  @AllowMissing()
  @IsObject()
  readonly args?: Record<string, any>;

  [key: string]: any;
}

export type ProjectType =
  | string
  | 'serviceContainer'
  | 'serverlessFunctions'
  | 'package'
  | 'infrastructure';

export class Project {
  constructor(init: Project) {
    Object.assign(this, init);
  }

  @AllowMissing()
  readonly type?: ProjectType;

  [key: string]: any;
}

/**
 * Refinement of the project configuration with known project types.
 */
export class ProjectConfiguration {
  constructor(init: ProjectConfiguration) {
    Object.assign(this, init);
  }

  @AllowMissing()
  @IsObject()
  @Type(() => Project)
  @ValidateNested()
  readonly project?: Project;

  [key: string]: any;
}

/**
 * Writes each project's configuration to a JSON file.
 * Sets the `causa.projectConfigurationsDirectory` configuration value.
 */
export class ProjectWriteConfigurationsProcessor {
  constructor(init: ProjectWriteConfigurationsProcessor) {
    Object.assign(this, init);
  }

  /**
   * The name of the WorkspaceFunction.
   */
  @Equals('ProjectWriteConfigurations')
  readonly name!: 'ProjectWriteConfigurations';

  [key: string]: any;
}

export type InfrastructureProcessor =
  | ProcessorInstruction
  | ProjectWriteConfigurationsProcessor;

/**
 * Configuration for scenarios.
 */
export class Scenario {
  constructor(init: Scenario) {
    Object.assign(this, init);
  }

  /**
   * Glob patterns to locate scenario files.
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly globs?: string[];

  [key: string]: any;
}

/**
 * A configuration for scenarios.
 */
export class ScenarioConfiguration {
  constructor(init: ScenarioConfiguration) {
    Object.assign(this, init);
  }

  /**
   * Configuration for scenarios.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => Scenario)
  @ValidateNested()
  readonly scenario?: Scenario;

  [key: string]: any;
}

export class ServerlessFunctionEventTrigger {
  constructor(init: ServerlessFunctionEventTrigger) {
    Object.assign(this, init);
  }

  /**
   * The type of trigger.
   */
  @Equals('event')
  readonly type!: 'event';

  /**
   * The ID of the topic triggering the endpoint.
   */
  @IsString()
  readonly topic!: string;

  [key: string]: any;
}

export class ServerlessFunctionGenericTrigger {
  constructor(init: ServerlessFunctionGenericTrigger) {
    Object.assign(this, init);
  }

  /**
   * The type of trigger.
   */
  @IsString()
  readonly type!: string;

  [key: string]: any;
}

/**
 * The data the function produces.
 */
export class ServerlessFunctionOutputs {
  constructor(init: ServerlessFunctionOutputs) {
    Object.assign(this, init);
  }

  /**
   * The list of event topics to which this function can publish events.
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly eventTopics?: string[];

  [key: string]: any;
}

/**
 * Configuration when building the artefact for serverless functions projects.
 */
export class ServerlessFunctionsBuild {
  constructor(init: ServerlessFunctionsBuild) {
    Object.assign(this, init);
  }

  /**
   * The glob patterns to include when building the artefact.
   * Language-specific modules may already include patterns by default, check their documentation before adding other patterns.
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly globPatterns?: string[];

  [key: string]: any;
}

/**
 * The event that triggers the function.
 */
export type ServerlessFunctionTrigger =
  | ServerlessFunctionGenericTrigger
  | ServerlessFunctionEventTrigger;

export class ServerlessFunction {
  constructor(init: ServerlessFunction) {
    Object.assign(this, init);
  }

  /**
   * The name of the function in the package.
   */
  @IsString()
  readonly entrypoint!: string;

  /**
   * The description of the function.
   */
  @AllowMissing()
  @IsString()
  readonly description?: string;

  /**
   * The event that triggers the function.
   */
  @Allow()
  readonly trigger!: ServerlessFunctionTrigger;

  /**
   * The data the function produces.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => ServerlessFunctionOutputs)
  @ValidateNested()
  readonly outputs?: ServerlessFunctionOutputs;

  [key: string]: any;
}

/**
 * Configuration for serverless functions projects, i.e. packages exposing functions that are deployed by a serverless platform.
 */
export class ServerlessFunctions {
  constructor(init: ServerlessFunctions) {
    Object.assign(this, init);
  }

  /**
   * The service managing the serverless functions (Google Cloud Functions, AWS Lambda, etc).
   */
  @AllowMissing()
  @IsString()
  readonly platform?: string;

  /**
   * Configuration when building the artefact for serverless functions projects.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => ServerlessFunctionsBuild)
  @ValidateNested()
  readonly build?: ServerlessFunctionsBuild;

  /**
   * The list of functions exposed by this project.
   */
  @AllowMissing()
  @IsObject()
  readonly functions?: Record<string, ServerlessFunction>;

  [key: string]: any;
}

/**
 * Configuration for serverless functions projects (Google Cloud Functions, AWS Lambda, etc).
 */
export class ServerlessFunctionsConfiguration {
  constructor(init: ServerlessFunctionsConfiguration) {
    Object.assign(this, init);
  }

  /**
   * Configuration for serverless functions projects, i.e. packages exposing functions that are deployed by a serverless platform.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => ServerlessFunctions)
  @ValidateNested()
  readonly serverlessFunctions?: ServerlessFunctions;

  [key: string]: any;
}

export class ServiceContainerCronTrigger {
  constructor(init: ServiceContainerCronTrigger) {
    Object.assign(this, init);
  }

  /**
   * The type of trigger.
   */
  @Equals('cron')
  readonly type!: 'cron';

  /**
   * The cron schedule expression for cron triggers.
   */
  @IsString()
  readonly schedule!: string;

  /**
   * The timezone for the cron schedule.
   */
  @AllowMissing()
  @IsString()
  readonly timezone?: string;

  [key: string]: any;
}

/**
 * The endpoints exposed by the service.
 */
export class ServiceContainerEndpoints {
  constructor(init: ServiceContainerEndpoints) {
    Object.assign(this, init);
  }

  /**
   * The HTTP endpoints exposed by the service.
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly http?: string[];

  [key: string]: any;
}

export class ServiceContainerEventTrigger {
  constructor(init: ServiceContainerEventTrigger) {
    Object.assign(this, init);
  }

  /**
   * The type of trigger.
   */
  @Equals('event')
  readonly type!: 'event';

  /**
   * The ID of the topic triggering the endpoint.
   */
  @IsString()
  readonly topic!: string;

  [key: string]: any;
}

/**
 * Configuration for an HTTP health check probe.
 */
export class ServiceContainerHealthCheckProbe {
  constructor(init: ServiceContainerHealthCheckProbe) {
    Object.assign(this, init);
  }

  /**
   * The HTTP path called by the probe. Defaults to `/health`.
   */
  @AllowMissing()
  @IsString()
  readonly path?: string;

  /**
   * The number of seconds after the container has started before the probe is first invoked.
   */
  @AllowMissing()
  @IsNumber()
  readonly initialDelay?: number;

  /**
   * The period in seconds at which the probe is invoked.
   */
  @AllowMissing()
  @IsNumber()
  readonly period?: number;

  /**
   * The number of seconds after which the probe times out.
   */
  @AllowMissing()
  @IsNumber()
  readonly timeout?: number;

  /**
   * The number of consecutive failures after which the probe is considered failed.
   */
  @AllowMissing()
  @IsNumber()
  readonly failureThreshold?: number;

  [key: string]: any;
}

/**
 * Configuration for the HTTP health check probes of the service.
 */
export class ServiceContainerHealthCheck {
  constructor(init: ServiceContainerHealthCheck) {
    Object.assign(this, init);
  }

  /**
   * Configuration for the startup probe.
   * Setting this to `null` disables the startup probe.
   */
  @AllowMissing()
  @IsNullable()
  @IsObject()
  @Type(() => ServiceContainerHealthCheckProbe)
  @ValidateNested()
  readonly startup?: ServiceContainerHealthCheckProbe | null;

  /**
   * Configuration for the liveness probe.
   * Setting this to `null` disables the liveness probe.
   */
  @AllowMissing()
  @IsNullable()
  @IsObject()
  @Type(() => ServiceContainerHealthCheckProbe)
  @ValidateNested()
  readonly liveness?: ServiceContainerHealthCheckProbe | null;

  [key: string]: any;
}

/**
 * The data this service produces.
 */
export class ServiceContainerOutputs {
  constructor(init: ServiceContainerOutputs) {
    Object.assign(this, init);
  }

  /**
   * The list of event topics to which this service can publish events.
   */
  @AllowMissing()
  @IsArray()
  @IsString({ each: true })
  readonly eventTopics?: string[];

  [key: string]: any;
}

export class ServiceContainerProject {
  constructor(init: ServiceContainerProject) {
    Object.assign(this, init);
  }

  /**
   * The deployed version of the service, which should correspond to a version tag in the container registry.
   */
  @AllowMissing()
  @IsString()
  readonly activeVersion?: string;

  [key: string]: any;
}

export class ServiceContainerTaskTrigger {
  constructor(init: ServiceContainerTaskTrigger) {
    Object.assign(this, init);
  }

  /**
   * The type of trigger.
   */
  @Equals('task')
  readonly type!: 'task';

  /**
   * The name of the queue for task triggers.
   */
  @IsString()
  readonly queue!: string;

  [key: string]: any;
}

/**
 * The endpoint called by the trigger.
 */
export class ServiceContainerTriggerEndpoint {
  constructor(init: ServiceContainerTriggerEndpoint) {
    Object.assign(this, init);
  }

  /**
   * The type of endpoint.
   */
  @IsString()
  readonly type!: string;

  /**
   * The path of the endpoint.
   */
  @IsString()
  readonly path!: string;

  [key: string]: any;
}

export class ServiceContainerGenericTrigger {
  constructor(init: ServiceContainerGenericTrigger) {
    Object.assign(this, init);
  }

  /**
   * The description of the trigger.
   */
  @AllowMissing()
  @IsString()
  readonly description?: string;

  /**
   * The type of trigger.
   */
  @IsString()
  readonly type!: string;

  /**
   * The endpoint called by the trigger.
   */
  @IsDefined()
  @IsObject()
  @Type(() => ServiceContainerTriggerEndpoint)
  @ValidateNested()
  readonly endpoint!: ServiceContainerTriggerEndpoint;

  [key: string]: any;
}

export type ServiceContainerTrigger =
  | ServiceContainerGenericTrigger
  | ServiceContainerEventTrigger
  | ServiceContainerCronTrigger
  | ServiceContainerTaskTrigger;

export type TemplateString = string;

/**
 * Configuration for infrastructure projects.
 */
export class Infrastructure {
  constructor(init: Infrastructure) {
    Object.assign(this, init);
  }

  /**
   * The list of processors that should be run prior to infrastructure operations to set up the workspace.
   * Processors should implement the `InfrastructureProcessor` interface.
   */
  @AllowMissing()
  @IsArray()
  readonly processors?: InfrastructureProcessor[];

  /**
   * Variables to be passed to the infrastructure as code system (e.g.  Terraform).
   * Supports rendering.
   */
  @AllowMissing()
  @IsObject()
  readonly variables?: Record<string, TemplateString>;

  /**
   * The location of the project, relative to the workspace root, that defines the infrastructure for a single environment.
   */
  @AllowMissing()
  @IsString()
  readonly environmentProject?: string;

  [key: string]: any;
}

/**
 * Configuration for infrastructure projects.
 */
export class InfrastructureConfiguration {
  constructor(init: InfrastructureConfiguration) {
    Object.assign(this, init);
  }

  /**
   * Configuration for infrastructure projects.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => Infrastructure)
  @ValidateNested()
  readonly infrastructure?: Infrastructure;

  [key: string]: any;
}

export type TemplateString_2 = string;

export class BuildSecretFile {
  constructor(init: BuildSecretFile) {
    Object.assign(this, init);
  }

  /**
   * The source file for the secret.
   */
  @Allow()
  readonly file!: TemplateString_2;

  [key: string]: any;
}

export class BuildSecretValue {
  constructor(init: BuildSecretValue) {
    Object.assign(this, init);
  }

  /**
   * The value of the secret.
   * In this case the value will be passed as an environment variable to the Docker command.
   */
  @Allow()
  readonly value!: TemplateString_2;

  [key: string]: any;
}

export type BuildSecret = BuildSecretFile | BuildSecretValue;

/**
 * Configuration for service container projects, i.e. services that are run as generic Docker containers.
 */
export class ServiceContainer {
  constructor(init: ServiceContainer) {
    Object.assign(this, init);
  }

  /**
   * The processor architecture used when building (and running) Docker images for the service.
   */
  @AllowMissing()
  @IsString()
  readonly architecture?: string;

  /**
   * The platform / orchestrator on which the service is deployed.
   */
  @AllowMissing()
  @IsString()
  readonly platform?: string;

  /**
   * The Dockerfile used to build the image for the service.
   * Language-specific modules may provide a default value for this.
   */
  @AllowMissing()
  @IsString()
  readonly buildFile?: string;

  /**
   * Docker build arguments when building the image for the service.
   * Supports rendering.
   */
  @AllowMissing()
  @IsObject()
  readonly buildArgs?: Record<string, TemplateString_2>;

  /**
   * Docker build --secret arguments to pass when building the image for the service.
   * Supports rendering.
   */
  @AllowMissing()
  @IsObject()
  readonly buildSecrets?: Record<string, BuildSecret>;

  /**
   * The endpoints exposed by the service.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => ServiceContainerEndpoints)
  @ValidateNested()
  readonly endpoints?: ServiceContainerEndpoints;

  /**
   * The environment variables passed to the service.
   */
  @AllowMissing()
  @IsObject()
  readonly environmentVariables?: Record<string, TemplateString_2>;

  /**
   * The maximum CPU allowed to the container, as a "quantity" Kubernetes type.
   */
  @AllowMissing()
  @IsString()
  readonly cpuLimit?: string;

  /**
   * The maximum memory allowed to the container, as a "quantity" Kubernetes type.
   */
  @AllowMissing()
  @IsString()
  readonly memoryLimit?: string;

  /**
   * The minimum number of instances of the service that should be running.
   */
  @AllowMissing()
  @IsNumber()
  readonly minInstances?: number;

  /**
   * The maximum number of instances of the service that should be running.
   */
  @AllowMissing()
  @IsNumber()
  readonly maxInstances?: number;

  /**
   * A map of triggers that call the service's endpoints when they occur.
   */
  @AllowMissing()
  @IsObject()
  readonly triggers?: Record<string, ServiceContainerTrigger>;

  /**
   * Configuration for the HTTP health check probes of the service.
   * Setting this to `null` disables both the startup and liveness probes.
   */
  @AllowMissing()
  @IsNullable()
  @IsObject()
  @Type(() => ServiceContainerHealthCheck)
  @ValidateNested()
  readonly healthCheck?: ServiceContainerHealthCheck | null;

  /**
   * The data this service produces.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => ServiceContainerOutputs)
  @ValidateNested()
  readonly outputs?: ServiceContainerOutputs;

  [key: string]: any;
}

/**
 * Configuration for service container projects.
 */
export class ServiceContainerConfiguration {
  constructor(init: ServiceContainerConfiguration) {
    Object.assign(this, init);
  }

  @AllowMissing()
  @IsObject()
  @Type(() => ServiceContainerProject)
  @ValidateNested()
  readonly project?: ServiceContainerProject;

  /**
   * Configuration for service container projects, i.e. services that are run as generic Docker containers.
   */
  @AllowMissing()
  @IsObject()
  @Type(() => ServiceContainer)
  @ValidateNested()
  readonly serviceContainer?: ServiceContainer;

  [key: string]: any;
}
