// This file was generated by the Causa command line. Do not edit it manually.

import {
  AllowMissing as _CausaRuntimeAllowMissing,
  IsNullable as _CausaRuntimeIsNullable,
} from '@causa/workspace/validation';
import { Type as _ClassTransformerType } from 'class-transformer';
import {
  Allow as _ClassValidatorAllow,
  Equals as _ClassValidatorEquals,
  IsArray as _ClassValidatorIsArray,
  IsBoolean as _ClassValidatorIsBoolean,
  IsDefined as _ClassValidatorIsDefined,
  IsIn as _ClassValidatorIsIn,
  IsNumber as _ClassValidatorIsNumber,
  IsObject as _ClassValidatorIsObject,
  IsString as _ClassValidatorIsString,
  ValidateNested as _ClassValidatorValidateNested,
} from 'class-validator';

/**
 * Configuration for the local emulators managed by `cs emulators`.
 */
export class CausaEmulators {
  constructor(init: CausaEmulators) {
    Object.assign(this, init);
  }

  /**
   * The file, relative to the workspace root, where the configuration returned by the emulators is written when running `cs emulators start`.
   * The file contains one `KEY="value"` line per configuration entry, and is meant to be loaded by tests and local runs (e.g. using `dotenv`).
   * Defaults to `.causa/emulators.env`. Set to `null` to disable writing the file entirely.
   */
  @_CausaRuntimeAllowMissing()
  @_CausaRuntimeIsNullable()
  @_ClassValidatorIsString()
  readonly environmentFile?: string | null;

  [key: string]: any;
}

export class CodeGenerator {
  constructor(init: CodeGenerator) {
    Object.assign(this, init);
  }

  /**
   * The name of the generator to run.
   */
  @_ClassValidatorIsString()
  readonly generator!: string;

  [key: string]: any;
}

/**
 * Configuration for the local Docker network.
 */
export class DockerNetwork {
  constructor(init: DockerNetwork) {
    Object.assign(this, init);
  }

  /**
   * The name of the local Docker network.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly name?: string;

  [key: string]: any;
}

/**
 * Configuration when using Docker in the workspace.
 */
export class Docker {
  constructor(init: Docker) {
    Object.assign(this, init);
  }

  /**
   * Configuration for the local Docker network.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => DockerNetwork)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly network?: DockerNetwork;

  [key: string]: any;
}

/**
 * The schema for the configuration of Docker.
 */
export class DockerConfiguration {
  constructor(init: DockerConfiguration) {
    Object.assign(this, init);
  }

  /**
   * Configuration when using Docker in the workspace.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => Docker)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly docker?: Docker;

  [key: string]: any;
}

/**
 * The format to which events are serialized when exchanged through the message broker.
 */
export enum EventsFormat {
  Json = 'json',
}

/**
 * Defines how topic definitions are found in the workspace.
 */
export class EventsTopics {
  constructor(init: EventsTopics) {
    Object.assign(this, init);
  }

  /**
   * The format string using groups from the regular expression used to make the topic full names.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly format?: string;

  /**
   * A list of glob patterns to find topic schema definition files in the workspace.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsArray()
  @_ClassValidatorIsString({ each: true })
  readonly globs?: string[];

  /**
   * The regular expression used to extract groups from the topic schemas file paths.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly regularExpression?: string;

  [key: string]: any;
}

/**
 * Configuration for events and how they are exchanged between services.
 */
export class Events {
  constructor(init: Events) {
    Object.assign(this, init);
  }

  /**
   * The format to which events are serialized when exchanged through the message broker.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsIn(['json'])
  readonly format?: EventsFormat;

  /**
   * The message broker used to exchange events between services.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly broker?: string;

  /**
   * Defines how topic definitions are found in the workspace.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => EventsTopics)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly topics?: EventsTopics;

  [key: string]: any;
}

/**
 * Configuration for events.
 */
export class EventsConfiguration {
  constructor(init: EventsConfiguration) {
    Object.assign(this, init);
  }

  /**
   * Configuration for events and how they are exchanged between services.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => Events)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly events?: Events;

  [key: string]: any;
}

/**
 * The schema format in which the model is defined.
 */
export enum ModelSchema {
  Jsonschema = 'jsonschema',
}

/**
 * Configuration for the business model definitions.
 */
export class Model {
  constructor(init: Model) {
    Object.assign(this, init);
  }

  /**
   * The schema format in which the model is defined.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsIn(['jsonschema'])
  readonly schema?: ModelSchema;

  /**
   * A list of glob patterns pointing to files containing the model definitions (schemas).
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsArray()
  @_ClassValidatorIsString({ each: true })
  readonly globs?: string[];

  /**
   * A list of code generators to run in a project when the `model generateCode` command is run.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => CodeGenerator)
  @_ClassValidatorIsArray()
  @_ClassValidatorIsObject({ each: true })
  @_ClassValidatorValidateNested()
  readonly codeGenerators?: CodeGenerator[];

  [key: string]: any;
}

export class ModelConfiguration {
  constructor(init: ModelConfiguration) {
    Object.assign(this, init);
  }

  /**
   * Configuration for the business model definitions.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => Model)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly model?: Model;

  [key: string]: any;
}

/**
 * Configuration for OpenAPI specifications-related operations.
 */
export class OpenApi {
  constructor(init: OpenApi) {
    Object.assign(this, init);
  }

  /**
   * An OpenAPI specification file to be used as the base when generating the specification for the entire workspace.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly global?: Record<string, any>;

  /**
   * A list of glob patterns matching OpenAPI specification files to merge when generating the specification for a project.
   * The globs are resolved relative to the project directory.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsArray()
  @_ClassValidatorIsString({ each: true })
  readonly specifications?: string[];

  /**
   * If set, the list of servers will be generated using a value from the configuration of each environment.
   * This should be the path to the configuration property containing the server URL.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly serversFromEnvironmentConfiguration?: string;

  [key: string]: any;
}

/**
 * Configuration for OpenAPI specifications-related operations.
 */
export class OpenApiConfiguration {
  constructor(init: OpenApiConfiguration) {
    Object.assign(this, init);
  }

  /**
   * Configuration for OpenAPI specifications-related operations.
   */
  @_CausaRuntimeAllowMissing()
  @_CausaRuntimeIsNullable()
  @_ClassTransformerType(() => OpenApi)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly openApi?: OpenApi | null;

  [key: string]: any;
}

export class ProcessorInstruction {
  constructor(init: ProcessorInstruction) {
    Object.assign(this, init);
  }

  /**
   * The name of the WorkspaceFunction.
   */
  @_ClassValidatorIsString()
  readonly name!: string;

  /**
   * Arguments for the workspace function.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly args?: Record<string, any>;

  [key: string]: any;
}

export type ProjectType =
  | string
  | 'serviceContainer'
  | 'serverlessFunctions'
  | 'package'
  | 'infrastructure';

export class Project {
  constructor(init: Project) {
    Object.assign(this, init);
  }

  @_CausaRuntimeAllowMissing()
  readonly type?: ProjectType;

  [key: string]: any;
}

/**
 * Refinement of the project configuration with known project types.
 */
export class ProjectConfiguration {
  constructor(init: ProjectConfiguration) {
    Object.assign(this, init);
  }

  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => Project)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly project?: Project;

  [key: string]: any;
}

/**
 * Writes each project's configuration to a JSON file.
 * Sets the `causa.projectConfigurationsDirectory` configuration value.
 */
export class ProjectWriteConfigurationsProcessor {
  constructor(init: ProjectWriteConfigurationsProcessor) {
    Object.assign(this, init);
  }

  /**
   * The name of the WorkspaceFunction.
   */
  @_ClassValidatorEquals('ProjectWriteConfigurations')
  readonly name!: 'ProjectWriteConfigurations';

  [key: string]: any;
}

export type InfrastructureProcessor =
  ProcessorInstruction | ProjectWriteConfigurationsProcessor;

/**
 * A masked environment variable, injected by the host into requests to the declared hosts.
 */
export class SandboxCredentialEnvironmentVariable {
  constructor(init: SandboxCredentialEnvironmentVariable) {
    Object.assign(this, init);
  }

  /**
   * The hosts the real value may be injected into. Wildcards such as `*.example.com` are supported.
   * The credential is never sent to any other host.
   */
  @_ClassValidatorIsArray()
  @_ClassValidatorIsString({ each: true })
  readonly hosts!: string[];

  [key: string]: any;
}

/**
 * The credentials the sandboxed process is allowed to use, masked from it and injected by the host.
 */
export class SandboxCredentials {
  constructor(init: SandboxCredentials) {
    Object.assign(this, init);
  }

  /**
   * A map of environment variables to mask, keyed by name. The sandboxed process sees an opaque sentinel
   * value instead of the real one; the host injects the real value into requests to the declared hosts.
   * The real value is read from the process spawning the command (its environment or `process.env`), so it
   * is never stored in the configuration.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly environment?: Record<string, SandboxCredentialEnvironmentVariable>;

  [key: string]: any;
}

/**
 * The filesystem restrictions for the profile. Reads follow a deny-then-allow model (everything readable
 * unless denied, then re-allowed within denied regions); writes follow an allow-only model. The workspace
 * root is always readable and writable, and the home directory is always denied for reads, so a profile
 * that needs to read a toolchain installed under the home directory must re-allow the relevant paths.
 */
export class SandboxFilesystem {
  constructor(init: SandboxFilesystem) {
    Object.assign(this, init);
  }

  /**
   * Additional paths whose reads are denied, on top of the always-denied home directory.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsArray()
  @_ClassValidatorIsString({ each: true })
  readonly denyRead?: string[];

  /**
   * Paths to re-allow reads for within denied regions, on top of the always-allowed workspace root.
   * Re-allowed paths take precedence over denied ones.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsArray()
  @_ClassValidatorIsString({ each: true })
  readonly allowRead?: string[];

  /**
   * Additional paths to allow writes to, on top of the always-allowed workspace root and the runtime's
   * default write paths (e.g. temporary directories).
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsArray()
  @_ClassValidatorIsString({ each: true })
  readonly allowWrite?: string[];

  /**
   * Paths to deny writes to within allowed regions. Denied paths take precedence over allowed ones.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsArray()
  @_ClassValidatorIsString({ each: true })
  readonly denyWrite?: string[];

  /**
   * Bypasses all filesystem restrictions when `true`.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsBoolean()
  readonly disabled?: boolean;

  [key: string]: any;
}

/**
 * The network restrictions for the profile. When omitted, all network access is blocked.
 */
export class SandboxNetwork {
  constructor(init: SandboxNetwork) {
    Object.assign(this, init);
  }

  /**
   * The list of domains the sandboxed process is allowed to reach. This is an allowlist: an empty list (or
   * an omitted network section) blocks all network access. Wildcards such as `*.example.com` are supported.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsArray()
  @_ClassValidatorIsString({ each: true })
  readonly allowedDomains?: string[];

  /**
   * The list of domains the sandboxed process is explicitly denied access to. Denied domains take
   * precedence over allowed ones.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsArray()
  @_ClassValidatorIsString({ each: true })
  readonly deniedDomains?: string[];

  /**
   * Whether the sandboxed process may bind to or connect to the loopback interface. Defaults to `false`.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsBoolean()
  readonly allowLocalBinding?: boolean;

  /**
   * The list of Unix socket paths the sandboxed process is allowed to use (macOS only).
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsArray()
  @_ClassValidatorIsString({ each: true })
  readonly allowUnixSockets?: string[];

  /**
   * Whether the sandboxed process is allowed to use any Unix socket.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsBoolean()
  readonly allowAllUnixSockets?: boolean;

  [key: string]: any;
}

/**
 * A sandbox profile describing how a process is restricted when run inside the OS-level sandbox.
 */
export class SandboxProfile {
  constructor(init: SandboxProfile) {
    Object.assign(this, init);
  }

  /**
   * The network restrictions for the profile. When omitted, all network access is blocked.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => SandboxNetwork)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly network?: SandboxNetwork;

  /**
   * The filesystem restrictions for the profile. Reads follow a deny-then-allow model (everything readable
   * unless denied, then re-allowed within denied regions); writes follow an allow-only model. The workspace
   * root is always readable and writable, and the home directory is always denied for reads, so a profile
   * that needs to read a toolchain installed under the home directory must re-allow the relevant paths.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => SandboxFilesystem)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly filesystem?: SandboxFilesystem;

  /**
   * The credentials the sandboxed process is allowed to use, masked from it and injected by the host.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => SandboxCredentials)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly credentials?: SandboxCredentials;

  /**
   * Weakens the Linux sandbox so it can run nested within an unprivileged container (e.g. in CI). This
   * reduces the security guarantees and should only be enabled when necessary.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsBoolean()
  readonly enableWeakerNestedSandbox?: boolean;

  /**
   * Weakens network isolation on macOS, required by some statically-linked binaries (e.g. Go) for TLS. This
   * reduces the security guarantees and should only be enabled when necessary.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsBoolean()
  readonly enableWeakerNetworkIsolation?: boolean;

  [key: string]: any;
}

/**
 * Additional causa properties used by workspace functions in this package.
 */
export class Causa {
  constructor(init: Causa) {
    Object.assign(this, init);
  }

  /**
   * The directory where project configurations are written by the ProjectWriteConfigurations processor.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly projectConfigurationsDirectory?: string;

  /**
   * Configuration for the local emulators managed by `cs emulators`.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => CausaEmulators)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly emulators?: CausaEmulators;

  /**
   * A map of sandbox profiles, keyed by an arbitrary name that can be referenced when running a sandboxed process.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly sandboxes?: Record<string, SandboxProfile>;

  [key: string]: any;
}

/**
 * A configuration with additional `causa` properties used by workspace functions in this package.
 */
export class CausaConfiguration {
  constructor(init: CausaConfiguration) {
    Object.assign(this, init);
  }

  /**
   * Additional causa properties used by workspace functions in this package.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => Causa)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly causa?: Causa;

  [key: string]: any;
}

/**
 * Configuration for scenarios.
 */
export class Scenario {
  constructor(init: Scenario) {
    Object.assign(this, init);
  }

  /**
   * Glob patterns to locate scenario files.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsArray()
  @_ClassValidatorIsString({ each: true })
  readonly globs?: string[];

  [key: string]: any;
}

/**
 * A configuration for scenarios.
 */
export class ScenarioConfiguration {
  constructor(init: ScenarioConfiguration) {
    Object.assign(this, init);
  }

  /**
   * Configuration for scenarios.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => Scenario)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly scenario?: Scenario;

  [key: string]: any;
}

export class ServerlessFunctionEventTrigger {
  constructor(init: ServerlessFunctionEventTrigger) {
    Object.assign(this, init);
  }

  /**
   * The type of trigger.
   */
  @_ClassValidatorEquals('event')
  readonly type!: 'event';

  /**
   * The ID of the topic triggering the endpoint.
   */
  @_ClassValidatorIsString()
  readonly topic!: string;

  [key: string]: any;
}

export class ServerlessFunctionGenericTrigger {
  constructor(init: ServerlessFunctionGenericTrigger) {
    Object.assign(this, init);
  }

  /**
   * The type of trigger.
   */
  @_ClassValidatorIsString()
  readonly type!: string;

  [key: string]: any;
}

/**
 * The data the function produces.
 */
export class ServerlessFunctionOutputs {
  constructor(init: ServerlessFunctionOutputs) {
    Object.assign(this, init);
  }

  /**
   * The list of event topics to which this function can publish events.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsArray()
  @_ClassValidatorIsString({ each: true })
  readonly eventTopics?: string[];

  [key: string]: any;
}

/**
 * Configuration when building the artefact for serverless functions projects.
 */
export class ServerlessFunctionsBuild {
  constructor(init: ServerlessFunctionsBuild) {
    Object.assign(this, init);
  }

  /**
   * The glob patterns to include when building the artefact.
   * Language-specific modules may already include patterns by default, check their documentation before adding other patterns.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsArray()
  @_ClassValidatorIsString({ each: true })
  readonly globPatterns?: string[];

  [key: string]: any;
}

/**
 * The event that triggers the function.
 */
export type ServerlessFunctionTrigger =
  ServerlessFunctionGenericTrigger | ServerlessFunctionEventTrigger;

export class ServerlessFunction {
  constructor(init: ServerlessFunction) {
    Object.assign(this, init);
  }

  /**
   * The name of the function in the package.
   */
  @_ClassValidatorIsString()
  readonly entrypoint!: string;

  /**
   * The description of the function.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly description?: string;

  /**
   * The event that triggers the function.
   */
  @_ClassValidatorAllow()
  readonly trigger!: ServerlessFunctionTrigger;

  /**
   * The data the function produces.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => ServerlessFunctionOutputs)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly outputs?: ServerlessFunctionOutputs;

  [key: string]: any;
}

/**
 * Configuration for serverless functions projects, i.e. packages exposing functions that are deployed by a serverless platform.
 */
export class ServerlessFunctions {
  constructor(init: ServerlessFunctions) {
    Object.assign(this, init);
  }

  /**
   * The service managing the serverless functions (Google Cloud Functions, AWS Lambda, etc).
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly platform?: string;

  /**
   * Configuration when building the artefact for serverless functions projects.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => ServerlessFunctionsBuild)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly build?: ServerlessFunctionsBuild;

  /**
   * The list of functions exposed by this project.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly functions?: Record<string, ServerlessFunction>;

  [key: string]: any;
}

/**
 * Configuration for serverless functions projects (Google Cloud Functions, AWS Lambda, etc).
 */
export class ServerlessFunctionsConfiguration {
  constructor(init: ServerlessFunctionsConfiguration) {
    Object.assign(this, init);
  }

  /**
   * Configuration for serverless functions projects, i.e. packages exposing functions that are deployed by a serverless platform.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => ServerlessFunctions)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly serverlessFunctions?: ServerlessFunctions;

  [key: string]: any;
}

export class ServiceContainerCronTrigger {
  constructor(init: ServiceContainerCronTrigger) {
    Object.assign(this, init);
  }

  /**
   * The type of trigger.
   */
  @_ClassValidatorEquals('cron')
  readonly type!: 'cron';

  /**
   * The cron schedule expression for cron triggers.
   */
  @_ClassValidatorIsString()
  readonly schedule!: string;

  /**
   * The timezone for the cron schedule.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly timezone?: string;

  [key: string]: any;
}

/**
 * The endpoints exposed by the service.
 */
export class ServiceContainerEndpoints {
  constructor(init: ServiceContainerEndpoints) {
    Object.assign(this, init);
  }

  /**
   * The HTTP endpoints exposed by the service.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsArray()
  @_ClassValidatorIsString({ each: true })
  readonly http?: string[];

  [key: string]: any;
}

export class ServiceContainerEventTrigger {
  constructor(init: ServiceContainerEventTrigger) {
    Object.assign(this, init);
  }

  /**
   * The type of trigger.
   */
  @_ClassValidatorEquals('event')
  readonly type!: 'event';

  /**
   * The ID of the topic triggering the endpoint.
   */
  @_ClassValidatorIsString()
  readonly topic!: string;

  [key: string]: any;
}

/**
 * Configuration for an HTTP health check probe.
 */
export class ServiceContainerHealthCheckProbe {
  constructor(init: ServiceContainerHealthCheckProbe) {
    Object.assign(this, init);
  }

  /**
   * The HTTP path called by the probe. Defaults to `/health`.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly path?: string;

  /**
   * The number of seconds after the container has started before the probe is first invoked.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsNumber()
  readonly initialDelay?: number;

  /**
   * The period in seconds at which the probe is invoked.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsNumber()
  readonly period?: number;

  /**
   * The number of seconds after which the probe times out.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsNumber()
  readonly timeout?: number;

  /**
   * The number of consecutive failures after which the probe is considered failed.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsNumber()
  readonly failureThreshold?: number;

  [key: string]: any;
}

/**
 * Configuration for the HTTP health check probes of the service.
 */
export class ServiceContainerHealthCheck {
  constructor(init: ServiceContainerHealthCheck) {
    Object.assign(this, init);
  }

  /**
   * Configuration for the startup probe.
   * Setting this to `null` disables the startup probe.
   */
  @_CausaRuntimeAllowMissing()
  @_CausaRuntimeIsNullable()
  @_ClassTransformerType(() => ServiceContainerHealthCheckProbe)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly startup?: ServiceContainerHealthCheckProbe | null;

  /**
   * Configuration for the liveness probe.
   * Setting this to `null` disables the liveness probe.
   */
  @_CausaRuntimeAllowMissing()
  @_CausaRuntimeIsNullable()
  @_ClassTransformerType(() => ServiceContainerHealthCheckProbe)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly liveness?: ServiceContainerHealthCheckProbe | null;

  [key: string]: any;
}

/**
 * The data this service produces.
 */
export class ServiceContainerOutputs {
  constructor(init: ServiceContainerOutputs) {
    Object.assign(this, init);
  }

  /**
   * The list of event topics to which this service can publish events.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsArray()
  @_ClassValidatorIsString({ each: true })
  readonly eventTopics?: string[];

  [key: string]: any;
}

export class ServiceContainerProject {
  constructor(init: ServiceContainerProject) {
    Object.assign(this, init);
  }

  /**
   * The deployed version of the service, which should correspond to a version tag in the container registry.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly activeVersion?: string;

  [key: string]: any;
}

export class ServiceContainerTaskTrigger {
  constructor(init: ServiceContainerTaskTrigger) {
    Object.assign(this, init);
  }

  /**
   * The type of trigger.
   */
  @_ClassValidatorEquals('task')
  readonly type!: 'task';

  /**
   * The name of the queue for task triggers.
   */
  @_ClassValidatorIsString()
  readonly queue!: string;

  [key: string]: any;
}

/**
 * The endpoint called by the trigger.
 */
export class ServiceContainerTriggerEndpoint {
  constructor(init: ServiceContainerTriggerEndpoint) {
    Object.assign(this, init);
  }

  /**
   * The type of endpoint.
   */
  @_ClassValidatorIsString()
  readonly type!: string;

  /**
   * The path of the endpoint.
   */
  @_ClassValidatorIsString()
  readonly path!: string;

  [key: string]: any;
}

export class ServiceContainerGenericTrigger {
  constructor(init: ServiceContainerGenericTrigger) {
    Object.assign(this, init);
  }

  /**
   * The description of the trigger.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly description?: string;

  /**
   * The type of trigger.
   */
  @_ClassValidatorIsString()
  readonly type!: string;

  /**
   * Whether the trigger is active. Defaults to `true`.
   * If `false`, the trigger shouldn't be deployed.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsBoolean()
  readonly enabled?: boolean;

  /**
   * A reference to a schema, relative to the project's root, that the trigger / endpoint accepts.
   * Unsupported for `event` triggers, which use the referenced topic's schema.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly dto?: string;

  /**
   * The endpoint called by the trigger.
   */
  @_ClassTransformerType(() => ServiceContainerTriggerEndpoint)
  @_ClassValidatorIsDefined()
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly endpoint!: ServiceContainerTriggerEndpoint;

  [key: string]: any;
}

export type ServiceContainerTrigger =
  | ServiceContainerGenericTrigger
  | ServiceContainerEventTrigger
  | ServiceContainerCronTrigger
  | ServiceContainerTaskTrigger;

export type TemplateString = string;

/**
 * Configuration for infrastructure projects.
 */
export class Infrastructure {
  constructor(init: Infrastructure) {
    Object.assign(this, init);
  }

  /**
   * The list of processors that should be run prior to infrastructure operations to set up the workspace.
   * Processors should implement the `InfrastructureProcessor` interface.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsArray()
  readonly processors?: InfrastructureProcessor[];

  /**
   * Variables to be passed to the infrastructure as code system (e.g.  Terraform).
   * Supports rendering.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly variables?: Record<string, TemplateString>;

  /**
   * The location of the project, relative to the workspace root, that defines the infrastructure for a single environment.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly environmentProject?: string;

  [key: string]: any;
}

/**
 * Configuration for infrastructure projects.
 */
export class InfrastructureConfiguration {
  constructor(init: InfrastructureConfiguration) {
    Object.assign(this, init);
  }

  /**
   * Configuration for infrastructure projects.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => Infrastructure)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly infrastructure?: Infrastructure;

  [key: string]: any;
}

export type TemplateString_2 = string;

export class BuildSecretFile {
  constructor(init: BuildSecretFile) {
    Object.assign(this, init);
  }

  /**
   * The source file for the secret.
   */
  @_ClassValidatorAllow()
  readonly file!: TemplateString_2;

  [key: string]: any;
}

export class BuildSecretValue {
  constructor(init: BuildSecretValue) {
    Object.assign(this, init);
  }

  /**
   * The value of the secret.
   * In this case the value will be passed as an environment variable to the Docker command.
   */
  @_ClassValidatorAllow()
  readonly value!: TemplateString_2;

  [key: string]: any;
}

export type BuildSecret = BuildSecretFile | BuildSecretValue;

/**
 * Configuration for service container projects, i.e. services that are run as generic Docker containers.
 */
export class ServiceContainer {
  constructor(init: ServiceContainer) {
    Object.assign(this, init);
  }

  /**
   * The processor architecture used when building (and running) Docker images for the service.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly architecture?: string;

  /**
   * The platform / orchestrator on which the service is deployed.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly platform?: string;

  /**
   * The Dockerfile used to build the image for the service.
   * Language-specific modules may provide a default value for this.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly buildFile?: string;

  /**
   * Docker build arguments when building the image for the service.
   * Supports rendering.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly buildArgs?: Record<string, TemplateString_2>;

  /**
   * Docker build --secret arguments to pass when building the image for the service.
   * Supports rendering.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly buildSecrets?: Record<string, BuildSecret>;

  /**
   * The endpoints exposed by the service.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => ServiceContainerEndpoints)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly endpoints?: ServiceContainerEndpoints;

  /**
   * The environment variables passed to the service.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly environmentVariables?: Record<string, TemplateString_2>;

  /**
   * The maximum CPU allowed to the container, as a "quantity" Kubernetes type.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly cpuLimit?: string;

  /**
   * The maximum memory allowed to the container, as a "quantity" Kubernetes type.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly memoryLimit?: string;

  /**
   * The minimum number of instances of the service that should be running.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsNumber()
  readonly minInstances?: number;

  /**
   * The maximum number of instances of the service that should be running.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsNumber()
  readonly maxInstances?: number;

  /**
   * A map of triggers that call the service's endpoints when they occur.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly triggers?: Record<string, ServiceContainerTrigger>;

  /**
   * Configuration for the HTTP health check probes of the service.
   * Setting this to `null` disables both the startup and liveness probes.
   */
  @_CausaRuntimeAllowMissing()
  @_CausaRuntimeIsNullable()
  @_ClassTransformerType(() => ServiceContainerHealthCheck)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly healthCheck?: ServiceContainerHealthCheck | null;

  /**
   * The data this service produces.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => ServiceContainerOutputs)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly outputs?: ServiceContainerOutputs;

  [key: string]: any;
}

/**
 * Configuration for service container projects.
 */
export class ServiceContainerConfiguration {
  constructor(init: ServiceContainerConfiguration) {
    Object.assign(this, init);
  }

  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => ServiceContainerProject)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly project?: ServiceContainerProject;

  /**
   * Configuration for service container projects, i.e. services that are run as generic Docker containers.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => ServiceContainer)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly serviceContainer?: ServiceContainer;

  [key: string]: any;
}
