// This file was generated by the Causa command line. Do not edit it manually.

import { AllowMissing as _CausaRuntimeAllowMissing } from '@causa/workspace/validation';
import { Type as _ClassTransformerType } from 'class-transformer';
import {
  Allow as _ClassValidatorAllow,
  IsArray as _ClassValidatorIsArray,
  IsBoolean as _ClassValidatorIsBoolean,
  IsDefined as _ClassValidatorIsDefined,
  IsIn as _ClassValidatorIsIn,
  IsInt as _ClassValidatorIsInt,
  IsObject as _ClassValidatorIsObject,
  IsString as _ClassValidatorIsString,
  ValidateNested as _ClassValidatorValidateNested,
} from 'class-validator';

/**
 * The value to match against. May be a templatable expression. Defaults to the output of the current step.
 */
export type ExpectationActual = string | Record<string, any>;

/**
 * The expected value. May be any JSON value supported by json-e / JavaScript (string, number, boolean, object, array, or null), and may contain `${ output(...) }` templates.
 */
export type ExpectationValue =
  string | number | boolean | null | ExpectationValue[] | Record<string, any>;

/**
 * Configuration for a single retry policy (number of attempts and delay between them).
 */
export class RetryPolicy {
  constructor(init: RetryPolicy) {
    Object.assign(this, init);
  }

  /**
   * The maximum number of attempts before giving up.
   */
  @_ClassValidatorIsInt()
  readonly maxAttempts!: number;

  /**
   * The delay in milliseconds between attempts.
   */
  @_ClassValidatorIsInt()
  readonly delay!: number;
}

/**
 * The type of the input value.
 */
export enum ScenarioInputType {
  String = 'string',
}

/**
 * Declaration of a single input that the scenario accepts.
 */
export class ScenarioInput {
  constructor(init: ScenarioInput) {
    Object.assign(this, init);
  }

  /**
   * A human-readable description of the input.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly description?: string;

  /**
   * The type of the input value.
   */
  @_ClassValidatorIsIn(['string'])
  readonly type!: ScenarioInputType;

  /**
   * The default value to use when the input is not provided at runtime.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly default?: string;
}

/**
 * A reference to a timeline definition associated with a scenario.
 */
export class ScenarioTimeline {
  constructor(init: ScenarioTimeline) {
    Object.assign(this, init);
  }

  /**
   * The path to the timeline definition file, relative to the scenario file.
   */
  @_ClassValidatorIsString()
  readonly path!: string;
}

/**
 * The function call performed by a step.
 */
export class StepCall {
  constructor(init: StepCall) {
    Object.assign(this, init);
  }

  /**
   * The name of the workspace function to invoke.
   */
  @_ClassValidatorIsString()
  readonly name!: string;

  /**
   * The arguments passed to the function. Free-form and may contain `${ ... }` template expressions.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly args?: Record<string, any>;
}

/**
 * A single expectation evaluated against the step's call output (or against `actual`).
 *
 * When `exact` is `false` (the default), `actual` is matched against `value` using `toMatchObject` semantics:
 * properties listed in `value` must match, but additional properties in `actual` (and its nested objects) are allowed.
 * When `exact` is `true`, `toEqual` semantics are used: `actual` must deeply equal `value`.
 *
 */
export class StepExpectation {
  constructor(init: StepExpectation) {
    Object.assign(this, init);
  }

  /**
   * A short human-readable description of what the expectation checks.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly description?: string;

  /**
   * Whether to require an exact deep-equality match. Defaults to `false`.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsBoolean()
  readonly exact?: boolean;

  /**
   * The value to match against. May be a templatable expression. Defaults to the output of the current step.
   */
  @_CausaRuntimeAllowMissing()
  readonly actual?: ExpectationActual;

  /**
   * The expected value. May be any JSON value supported by json-e / JavaScript (string, number, boolean, object, array, or null), and may contain `${ output(...) }` templates.
   */
  @_ClassValidatorAllow()
  readonly value!: ExpectationValue;
}

/**
 * A single step within a scenario.
 *
 * A step calls a workspace function and optionally validates the output against an expectation.
 *
 */
export class ScenarioStep {
  constructor(init: ScenarioStep) {
    Object.assign(this, init);
  }

  /**
   * A short human-readable name for the step.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly name?: string;

  /**
   * A longer description of what the step does.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly description?: string;

  @_ClassTransformerType(() => StepCall)
  @_ClassValidatorIsDefined()
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly call!: StepCall;

  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => RetryPolicy)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly retry?: RetryPolicy;

  /**
   * The expectations evaluated against the step's call output, in order.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => StepExpectation)
  @_ClassValidatorIsArray()
  @_ClassValidatorIsObject({ each: true })
  @_ClassValidatorValidateNested()
  readonly expectations?: StepExpectation[];

  /**
   * IDs of other steps this step explicitly depends on. The referenced steps are guaranteed to have completed
   * successfully before this step runs, even when no `output('<id>')` template references them.
   *
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsArray()
  @_ClassValidatorIsString({ each: true })
  readonly after?: string[];
}

/**
 * The root document of a scenario file.
 */
export class Scenario {
  constructor(init: Scenario) {
    Object.assign(this, init);
  }

  /**
   * The unique identifier of the scenario.
   */
  @_ClassValidatorIsString()
  readonly id!: string;

  /**
   * A human-readable description of what the scenario does.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly description?: string;

  /**
   * Inputs accepted by the scenario, keyed by input name. Referenced as `${ input('<name>') }` in steps.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly inputs?: Record<string, ScenarioInput>;

  /**
   * Default `args` to set when a step calls a given workspace function, keyed by function name. Per-step `args` are
   * shallow-merged on top of these defaults. Values may contain `${ ... }` template expressions, evaluated when
   * collecting dependencies and right before each step call.
   *
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsObject()
  readonly defaultCallArgs?: Record<string, Record<string, any>>;

  /**
   * The steps of the scenario, keyed by step ID. Outputs of previous steps are referenced as
   * `${ output('<stepId>') }`.
   *
   */
  @_ClassValidatorIsObject()
  readonly steps!: Record<string, ScenarioStep>;

  /**
   * An optional timeline displayed while the scenario runs, and after it completes, to inspect its results.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => ScenarioTimeline)
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly timeline?: ScenarioTimeline;
}
