// This file was generated by the Causa command line. Do not edit it manually.

import { AllowMissing } from '@causa/workspace/validation';
import { Type } from 'class-transformer';
import {
  IsArray,
  IsBoolean,
  IsDefined,
  IsIn,
  IsInt,
  IsNumber,
  IsObject,
  IsString,
  ValidateNested,
} from 'class-validator';

/**
 * The type of the input value.
 */
export enum ScenarioInputType {
  String = 'string',
}

/**
 * Declaration of a single input that the scenario accepts.
 */
export class ScenarioInput {
  constructor(init: ScenarioInput) {
    Object.assign(this, init);
  }

  /**
   * The default value to use when the input is not provided at runtime.
   */
  @AllowMissing()
  @IsString()
  readonly default?: string;

  /**
   * A human-readable description of the input.
   */
  @AllowMissing()
  @IsString()
  readonly description?: string;

  /**
   * The type of the input value.
   */
  @IsIn(['string'])
  readonly type!: ScenarioInputType;
}

/**
 * The function call performed by a step.
 */
export class StepCall {
  constructor(init: StepCall) {
    Object.assign(this, init);
  }

  /**
   * The arguments passed to the function. Free-form and may contain `${ ... }` template expressions.
   */
  @AllowMissing()
  @IsObject()
  readonly args?: { [key: string]: any };

  /**
   * The name of the workspace function to invoke.
   */
  @IsString()
  readonly name!: string;
}

/**
 * A single expectation evaluated against the step's call output (or against `actual`).
 *
 * When `exact` is `false` (the default), `actual` is matched against `value` using `toMatchObject` semantics:
 * properties listed in `value` must match, but additional properties in `actual` (and its nested objects) are allowed.
 * When `exact` is `true`, `toEqual` semantics are used: `actual` must deeply equal `value`.
 *
 */
export class StepExpectation {
  constructor(init: StepExpectation) {
    Object.assign(this, init);
  }

  /**
   * The value to match against. May be a templatable expression. Defaults to the output of the current step.
   */
  @AllowMissing()
  readonly actual?: any;

  /**
   * A short human-readable description of what the expectation checks.
   */
  @AllowMissing()
  @IsString()
  readonly description?: string;

  /**
   * Whether to require an exact deep-equality match. Defaults to `false`.
   */
  @AllowMissing()
  @IsBoolean()
  readonly exact?: boolean;

  /**
   * The expected value. May contain `${ match(...) }` and `${ output(...) }` templates.
   */
  readonly value!: any;
}

/**
 * Configuration for a single retry policy (number of attempts and delay between them).
 */
export class RetryPolicy {
  constructor(init: RetryPolicy) {
    Object.assign(this, init);
  }

  /**
   * The delay in milliseconds between attempts.
   */
  @IsNumber()
  readonly delay!: number;

  /**
   * The maximum number of attempts before giving up.
   */
  @IsInt()
  readonly maxAttempts!: number;
}

/**
 * A single step within a scenario.
 *
 * A step calls a workspace function and optionally validates the output against an expectation.
 *
 */
export class ScenarioStep {
  constructor(init: ScenarioStep) {
    Object.assign(this, init);
  }

  @IsObject()
  @ValidateNested()
  @IsDefined()
  @Type(() => StepCall)
  readonly call!: StepCall;

  /**
   * A longer description of what the step does.
   */
  @AllowMissing()
  @IsString()
  readonly description?: string;

  /**
   * The expectations evaluated against the step's call output, in order.
   */
  @AllowMissing()
  @IsArray()
  @IsObject({ each: true })
  @ValidateNested()
  @Type(() => StepExpectation)
  readonly expectations?: StepExpectation[];

  /**
   * A short human-readable name for the step.
   */
  @AllowMissing()
  @IsString()
  readonly name?: string;

  @AllowMissing()
  @IsObject()
  @ValidateNested()
  @Type(() => RetryPolicy)
  readonly retry?: RetryPolicy;
}

/**
 * The root document of a scenario file.
 */
export class Scenario {
  constructor(init: Scenario) {
    Object.assign(this, init);
  }

  /**
   * Default `args` to set when a step calls a given workspace function, keyed by function name. Per-step `args` are
   * shallow-merged on top of these defaults. Values may contain `${ ... }` template expressions, evaluated when
   * collecting dependencies and right before each step call.
   *
   */
  @AllowMissing()
  @IsObject()
  readonly defaultCallArgs?: { [key: string]: { [key: string]: any } };

  /**
   * A human-readable description of what the scenario does.
   */
  @AllowMissing()
  @IsString()
  readonly description?: string;

  /**
   * The unique identifier of the scenario.
   */
  @IsString()
  readonly id!: string;

  /**
   * Inputs accepted by the scenario, keyed by input name. Referenced as `${ input('<name>') }` in steps.
   */
  @AllowMissing()
  @IsObject()
  readonly inputs?: { [key: string]: ScenarioInput };

  /**
   * The steps of the scenario, keyed by step ID. Outputs of previous steps are referenced as
   * `${ output('<stepId>') }`.
   *
   */
  @IsObject()
  readonly steps!: { [key: string]: ScenarioStep };
}
