import { CliCommand, type ParentCliCommandDefinition } from '@causa/cli';
import { WorkspaceFunction } from '@causa/workspace';
import { IsObject, IsString } from 'class-validator';

/**
 * The `model` parent command, grouping all commands related to business modelling, e.g. generating code from schemas.
 */
export const modelCommandDefinition: ParentCliCommandDefinition = {
  name: 'model',
  description: 'Manages business modelling, and code generation from it.',
};

/**
 * Runs all the configured model code generators.
 * Returns the list of files generated by the code generators.
 */
@CliCommand({
  parent: modelCommandDefinition,
  name: 'generateCode',
  description: `Runs all the configured model code generators.`,
  summary: `Runs all the configured model code generators.`,
  aliases: ['genCode'],
  outputFn: (files) => console.log(files.join('\n')),
})
export abstract class ModelGenerateCode extends WorkspaceFunction<
  Promise<string[]>
> {}

/**
 * Runs the given model code generator, and returns the list of files generated by it.
 * This should be implemented by each code generator for its corresponding {@link ModelRunCodeGenerator.generator} name.
 */
export abstract class ModelRunCodeGenerator extends WorkspaceFunction<
  Promise<string[]>
> {
  /**
   * The name of the code generator to run.
   */
  @IsString()
  readonly generator!: string;

  /**
   * The configuration for the code generator.
   */
  @IsObject()
  readonly configuration!: Record<string, unknown>;
}

/**
 * Inputs for a code generator, parsed from its configuration.
 */
export type CodeGeneratorInputs = {
  /**
   * Whether to include schema files for events referenced in the project.
   * This is only provided for information. If this is `true`, {@link CodeGeneratorInputs.files} will contain the schema
   * files for the events.
   */
  includeEvents: boolean;

  /**
   * The globs to use to find schema files.
   * This is only provided for information. If this is set, {@link CodeGeneratorInputs.files} will contain the schema
   * files matching the globs.
   */
  globs: string[];

  /**
   * The files to use as input for the code generator.
   */
  files: string[];

  /**
   * A list of properties that may exist in JSONSchema files and contain nested schemas.
   * This should be passed to the code generator configuration.
   */
  nestedSchemas?: string[];

  /**
   * If `true`, JSONSchema files that are referenced by other schemas should be included in the input data, along with
   * their nested schemas.
   * This should be passed to the code generator configuration.
   */
  includeFullReferences?: boolean;
};

/**
 * Parses the inputs for a code generator, based on its configuration.
 * This expects standard properties in the configuration (all are optional):
 * - `includeEvents`: boolean.
 * - `globs`: string[].
 * - `nestedSchemas`: string[].
 * - `includeReferences`: boolean.
 */
export abstract class ModelParseCodeGeneratorInputs extends WorkspaceFunction<
  Promise<CodeGeneratorInputs>
> {
  /**
   * The configuration for the code generator.
   */
  @IsObject()
  readonly configuration!: Record<string, unknown>;
}
